/**
 * 课程运营「今日执行 / 排课日历」前端验收样本（与 Courses 周视图 2026-05-04～05-10 对齐）。
 * 仅追加数据，不替代业务逻辑。
 */
import type { Attendance, Booking, CourseSession } from '../types';

/** 与 weekDays Mon 05/04 … Sun 05/10 及 getDayIndexFromIso 对齐的场次（CourseSession 形态，经 toScheduleEvent 进入日历） */
export const COURSE_OPS_SCENARIO_EVENTS: CourseSession[] = [
  {
    id: 'ops-qa-draft',
    courseId: 'course-flow-yoga',
    title: '验收｜草稿排课',
    status: 'draft',
    storeId: '1',
    roomId: '101',
    teacherId: '4',
    startAt: '2026-05-04T15:00:00+08:00',
    endAt: '2026-05-04T16:00:00+08:00',
    capacity: 12,
    bookedCount: 0,
    publishStatus: 'draft',
    bookingStatus: 'not_open',
    sessionStatus: 'upcoming',
    exceptionStatus: 'none',
    settlementStatus: 'not_started',
  },
  {
    id: 'ops-qa-bookable',
    courseId: 'course-flow-yoga',
    title: '验收｜已发布可预约',
    status: 'published',
    storeId: '1',
    roomId: '101',
    teacherId: '4',
    startAt: '2026-05-05T09:00:00+08:00',
    endAt: '2026-05-05T10:00:00+08:00',
    capacity: 12,
    bookedCount: 2,
    publishStatus: 'published',
    bookingStatus: 'bookable',
    sessionStatus: 'upcoming',
    exceptionStatus: 'none',
    settlementStatus: 'not_started',
    price: 180,
  },
  {
    id: 'ops-qa-full',
    courseId: 'course-pilates-reformer',
    title: '验收｜已满员',
    status: 'published',
    storeId: '1',
    roomId: '102',
    teacherId: '2',
    startAt: '2026-05-05T11:30:00+08:00',
    endAt: '2026-05-05T12:30:00+08:00',
    capacity: 3,
    bookedCount: 3,
    publishStatus: 'published',
    bookingStatus: 'full',
    sessionStatus: 'upcoming',
    exceptionStatus: 'none',
    settlementStatus: 'not_started',
    price: 480,
  },
  {
    id: 'ops-qa-cancelled',
    courseId: 'course-flow-yoga',
    title: '验收｜已取消课程',
    status: 'cancelled',
    storeId: '1',
    roomId: '101',
    teacherId: '4',
    startAt: '2026-05-05T13:00:00+08:00',
    endAt: '2026-05-05T14:00:00+08:00',
    capacity: 12,
    bookedCount: 1,
    publishStatus: 'canceled',
    bookingStatus: 'suspended',
    sessionStatus: 'canceled',
    exceptionStatus: 'cancel_pending',
    settlementStatus: 'exception_hold',
    notes: '【取消】原因：老师临时请假；（操作：运营管理员）',
  },
  {
    id: 'ops-qa-reschedule',
    courseId: 'course-pilates-reformer',
    title: '验收｜已调课',
    status: 'rescheduled',
    storeId: '1',
    roomId: '102',
    teacherId: '2',
    startAt: '2026-05-05T14:30:00+08:00',
    endAt: '2026-05-05T15:30:00+08:00',
    capacity: 6,
    bookedCount: 1,
    publishStatus: 'published',
    bookingStatus: 'bookable',
    sessionStatus: 'rescheduled',
    exceptionStatus: 'reschedule_pending',
    settlementStatus: 'exception_hold',
    notes: '【调课】原因：时间调整；说明：会员已预约，等待后续通知规则接入。（操作：运营管理员）',
  },
  {
    id: 'ops-qa-substitute',
    courseId: 'course-flow-yoga',
    title: '验收｜代课中',
    status: 'published',
    storeId: '1',
    roomId: '101',
    teacherId: '2',
    teacherName: '代课老师 Joyce',
    startAt: '2026-05-05T17:30:00+08:00',
    endAt: '2026-05-05T18:30:00+08:00',
    capacity: 12,
    bookedCount: 1,
    publishStatus: 'published',
    bookingStatus: 'bookable',
    sessionStatus: 'substitute',
    exceptionStatus: 'substitute_pending',
    settlementStatus: 'exception_hold',
    notes: '【代课】原老师：方方；代课老师：Joyce；原因：原老师请假；（操作：运营管理员）',
  },
  {
    id: 'ops-qa-ended-no-att',
    courseId: 'course-flow-yoga',
    title: '验收｜已结束无到课',
    status: 'published',
    storeId: '1',
    roomId: '101',
    teacherId: '4',
    startAt: '2026-05-05T07:30:00+08:00',
    endAt: '2026-05-05T08:30:00+08:00',
    capacity: 12,
    bookedCount: 1,
    publishStatus: 'published',
    bookingStatus: 'closed',
    sessionStatus: 'ended',
    exceptionStatus: 'none',
    settlementStatus: 'not_started',
  },
  {
    id: 'ops-qa-archivable',
    courseId: 'course-private-core',
    title: '验收｜可归档课程',
    status: 'published',
    storeId: '1',
    roomId: '201',
    teacherId: '2',
    startAt: '2026-05-05T10:15:00+08:00',
    endAt: '2026-05-05T11:15:00+08:00',
    capacity: 1,
    bookedCount: 1,
    publishStatus: 'published',
    bookingStatus: 'closed',
    sessionStatus: 'ended',
    exceptionStatus: 'none',
    settlementStatus: 'not_started',
    price: 680,
  },
  {
    id: 'ops-qa-done-revenue',
    courseId: 'course-pilates-reformer',
    title: '验收｜已完课已确认收入',
    status: 'completed',
    storeId: '1',
    roomId: '102',
    teacherId: '2',
    startAt: '2026-05-05T16:00:00+08:00',
    endAt: '2026-05-05T17:00:00+08:00',
    capacity: 6,
    bookedCount: 1,
    publishStatus: 'published',
    bookingStatus: 'closed',
    sessionStatus: 'completed',
    exceptionStatus: 'none',
    settlementStatus: 'revenue_confirmed',
    notes: '【完课】已完成课程归档，生成耗课、老师课时与确认收入估算记录。（操作：运营管理员）',
    price: 480,
  },
  {
    id: 'ops-qa-exception',
    courseId: 'course-flow-yoga',
    title: '验收｜异常待处理',
    status: 'published',
    storeId: '1',
    roomId: '101',
    teacherId: '4',
    startAt: '2026-05-06T10:00:00+08:00',
    endAt: '2026-05-06T11:00:00+08:00',
    capacity: 12,
    bookedCount: 2,
    publishStatus: 'published',
    bookingStatus: 'closed',
    sessionStatus: 'exception_pending',
    exceptionStatus: 'attendance_conflict',
    settlementStatus: 'exception_hold',
    notes: '【异常】签到人数与预约人数不一致，等待处理。（操作：运营管理员）',
  },
];

export const COURSE_OPS_SCENARIO_BOOKINGS: Booking[] = [
  { id: 'b-ops-qa-bookable-1', memberId: '1', courseSessionId: 'ops-qa-bookable', status: 'booked', bookedAt: '2026-05-04T10:00:00+08:00', source: 'admin' },
  { id: 'b-ops-qa-bookable-2', memberId: '2', courseSessionId: 'ops-qa-bookable', status: 'booked', bookedAt: '2026-05-04T11:00:00+08:00', source: 'member_app' },
  { id: 'b-ops-qa-full-1', memberId: '1', courseSessionId: 'ops-qa-full', status: 'booked', bookedAt: '2026-05-04T12:00:00+08:00', source: 'admin' },
  { id: 'b-ops-qa-full-2', memberId: '2', courseSessionId: 'ops-qa-full', status: 'booked', bookedAt: '2026-05-04T12:05:00+08:00', source: 'admin' },
  { id: 'b-ops-qa-full-3', memberId: '3', courseSessionId: 'ops-qa-full', status: 'booked', bookedAt: '2026-05-04T12:10:00+08:00', source: 'admin' },
  { id: 'b-ops-qa-cancelled-1', memberId: '5', courseSessionId: 'ops-qa-cancelled', status: 'booked', bookedAt: '2026-05-04T09:00:00+08:00', source: 'front_desk' },
  { id: 'b-ops-qa-reschedule-1', memberId: '1', courseSessionId: 'ops-qa-reschedule', status: 'booked', bookedAt: '2026-05-04T13:00:00+08:00', source: 'admin' },
  { id: 'b-ops-qa-substitute-1', memberId: '3', courseSessionId: 'ops-qa-substitute', status: 'booked', bookedAt: '2026-05-04T14:00:00+08:00', source: 'member_app' },
  { id: 'b-ops-qa-ended-no-1', memberId: '2', courseSessionId: 'ops-qa-ended-no-att', status: 'booked', bookedAt: '2026-05-04T08:00:00+08:00', source: 'admin' },
  { id: 'b-ops-qa-archivable-1', memberId: '1', courseSessionId: 'ops-qa-archivable', status: 'booked', bookedAt: '2026-05-04T09:30:00+08:00', source: 'admin' },
  { id: 'b-ops-qa-done-1', memberId: '5', courseSessionId: 'ops-qa-done-revenue', status: 'booked', bookedAt: '2026-05-04T15:00:00+08:00', source: 'member_app' },
  { id: 'b-ops-qa-exception-1', memberId: '1', courseSessionId: 'ops-qa-exception', status: 'booked', bookedAt: '2026-05-05T09:00:00+08:00', source: 'admin' },
  { id: 'b-ops-qa-exception-2', memberId: '2', courseSessionId: 'ops-qa-exception', status: 'booked', bookedAt: '2026-05-05T09:05:00+08:00', source: 'admin' },
  { id: 'b-ops-qa-exception-lc', memberId: '3', courseSessionId: 'ops-qa-exception', status: 'late_cancelled', bookedAt: '2026-05-05T08:00:00+08:00', cancelledAt: '2026-05-06T09:30:00+08:00', cancelReason: '临时调整' },
];

export const COURSE_OPS_SCENARIO_ATTENDANCES: Attendance[] = [
  {
    id: 'att-ops-qa-archivable-1',
    memberId: '1',
    courseSessionId: 'ops-qa-archivable',
    bookingId: 'b-ops-qa-archivable-1',
    status: 'checked_in',
    checkedInAt: '2026-05-05T10:05:00+08:00',
  },
  {
    id: 'att-ops-qa-done-1',
    memberId: '5',
    courseSessionId: 'ops-qa-done-revenue',
    bookingId: 'b-ops-qa-done-1',
    status: 'consumed',
    checkedInAt: '2026-05-05T15:50:00+08:00',
    attendedAt: '2026-05-05T16:00:00+08:00',
    consumedAt: '2026-05-05T17:05:00+08:00',
  },
  {
    id: 'att-ops-qa-ended-absent',
    memberId: '2',
    courseSessionId: 'ops-qa-ended-no-att',
    bookingId: 'b-ops-qa-ended-no-1',
    status: 'absent',
    notes: '未到课',
  },
  {
    id: 'att-ops-qa-exception-absent',
    memberId: '1',
    courseSessionId: 'ops-qa-exception',
    bookingId: 'b-ops-qa-exception-1',
    status: 'absent',
    notes: '预约在册但未签到',
  },
];
