/**
 * 产品与合同模块「订单详情」验收样本（仅前端合并展示，不落库、不触发真实收退款）。
 */
import type { Contract, MemberAsset, Order, Payment, Refund } from '../types';

const T = '2026-05-10T10:00:00+08:00';

/** 1 完整闭环：已支付 + 合同生效 + 支付流水 + 会员资产，无退款 */
export const MALL_ORDER_SCENARIO_ORDERS: Order[] = [
  {
    id: 'ord-sc-01',
    memberId: '5',
    status: 'fulfilled',
    items: [
      {
        id: 'ord-sc-01-i1',
        orderId: 'ord-sc-01',
        productType: 'card',
        productId: 'c8',
        productName: '验收｜完整闭环订单',
        quantity: 1,
        unitPrice: 11800,
        totalAmount: 11800,
        memberAssetId: 'asset-sc-01',
      },
    ],
    totalAmount: 11800,
    paidAmount: 11800,
    contractId: 'contract-sc-01',
    createdAt: T,
    updatedAt: T,
    storeId: '1',
  },
  /** 2 已支付、合同待签、有支付、无资产 */
  {
    id: 'ord-sc-02',
    memberId: '1',
    status: 'paid',
    items: [
      {
        id: 'ord-sc-02-i1',
        orderId: 'ord-sc-02',
        productType: 'card',
        productId: 'c4',
        productName: '验收｜已支付合同待签',
        quantity: 1,
        unitPrice: 12800,
        totalAmount: 12800,
      },
    ],
    totalAmount: 12800,
    paidAmount: 12800,
    contractId: 'contract-sc-02',
    createdAt: T,
    storeId: '1',
  },
  /** 3 合同已签、有支付、无会员资产 */
  {
    id: 'ord-sc-03',
    memberId: '3',
    status: 'fulfilled',
    items: [
      {
        id: 'ord-sc-03-i1',
        orderId: 'ord-sc-03',
        productType: 'card',
        productId: 'c5',
        productName: '验收｜合同已签资产未发',
        quantity: 1,
        unitPrice: 8800,
        totalAmount: 8800,
      },
    ],
    totalAmount: 8800,
    paidAmount: 8800,
    contractId: 'contract-sc-03',
    createdAt: T,
    storeId: '1',
  },
  /** 4 订单显示已履约已付清，但无支付流水 */
  {
    id: 'ord-sc-04',
    memberId: '102',
    status: 'fulfilled',
    items: [
      {
        id: 'ord-sc-04-i1',
        orderId: 'ord-sc-04',
        productType: 'point',
        productId: 'p1',
        productName: '验收｜已支付无支付流水',
        quantity: 1,
        unitPrice: 2000,
        totalAmount: 2000,
      },
    ],
    totalAmount: 2000,
    paidAmount: 2000,
    createdAt: T,
    storeId: '1',
  },
  /** 5 有退款记录（资产已用尽，不触发「资产仍可用」风险） */
  {
    id: 'ord-sc-05',
    memberId: '3',
    status: 'partially_refunded',
    items: [
      {
        id: 'ord-sc-05-i1',
        orderId: 'ord-sc-05',
        productType: 'point',
        productId: 'p2',
        productName: '验收｜有退款记录',
        quantity: 1,
        unitPrice: 500,
        totalAmount: 500,
        memberAssetId: 'asset-sc-05',
      },
    ],
    totalAmount: 500,
    paidAmount: 500,
    contractId: 'contract-sc-05',
    createdAt: T,
    storeId: '1',
  },
  /** 6 已退款 + 资产仍生效且有余额 */
  {
    id: 'ord-sc-06',
    memberId: '5',
    status: 'refunded',
    items: [
      {
        id: 'ord-sc-06-i1',
        orderId: 'ord-sc-06',
        productType: 'card',
        productId: 'c8',
        productName: '验收｜已退款资产仍可用',
        quantity: 1,
        unitPrice: 1999,
        totalAmount: 1999,
        memberAssetId: 'asset-sc-06',
      },
    ],
    totalAmount: 1999,
    paidAmount: 1999,
    contractId: 'contract-sc-06',
    createdAt: T,
    storeId: '1',
  },
  /** 7 已取消、无有效支付、无资产 */
  {
    id: 'ord-sc-07',
    memberId: '103',
    status: 'cancelled',
    items: [
      {
        id: 'ord-sc-07-i1',
        orderId: 'ord-sc-07',
        productType: 'card',
        productId: 'c8',
        productName: '验收｜订单已取消',
        quantity: 1,
        unitPrice: 2999,
        totalAmount: 2999,
      },
    ],
    totalAmount: 2999,
    paidAmount: 0,
    contractId: 'contract-sc-07',
    createdAt: T,
    storeId: '1',
  },
  /** 8 部分退款，资产仍有余量（权益登记口径） */
  {
    id: 'ord-sc-08',
    memberId: '3',
    status: 'partially_refunded',
    items: [
      {
        id: 'ord-sc-08-i1',
        orderId: 'ord-sc-08',
        productType: 'point',
        productId: 'p2',
        productName: '验收｜部分退款资产仍有余量',
        quantity: 1,
        unitPrice: 800,
        totalAmount: 800,
        memberAssetId: 'asset-sc-08',
      },
    ],
    totalAmount: 800,
    paidAmount: 800,
    contractId: 'contract-sc-08',
    createdAt: T,
    updatedAt: T,
    storeId: '1',
  },
  /** 9 全额退款，资产已作废 */
  {
    id: 'ord-sc-09',
    memberId: '5',
    status: 'refunded',
    items: [
      {
        id: 'ord-sc-09-i1',
        orderId: 'ord-sc-09',
        productType: 'card',
        productId: 'c8',
        productName: '验收｜全额退款资产已作废',
        quantity: 1,
        unitPrice: 3500,
        totalAmount: 3500,
        memberAssetId: 'asset-sc-09',
      },
    ],
    totalAmount: 3500,
    paidAmount: 3500,
    contractId: 'contract-sc-09',
    createdAt: T,
    updatedAt: T,
    storeId: '1',
  },
  /** 10 已完成退款但未关联会员资产 */
  {
    id: 'ord-sc-10',
    memberId: '2',
    status: 'paid',
    items: [
      {
        id: 'ord-sc-10-i1',
        orderId: 'ord-sc-10',
        productType: 'card',
        productId: 'c4',
        productName: '验收｜退款未绑定资产',
        quantity: 1,
        unitPrice: 3000,
        totalAmount: 3000,
      },
    ],
    totalAmount: 3000,
    paidAmount: 3000,
    contractId: 'contract-sc-10',
    createdAt: T,
    updatedAt: T,
    storeId: '1',
  },
];

export const MALL_ORDER_SCENARIO_CONTRACTS: Contract[] = [
  {
    id: 'contract-sc-01',
    memberId: '5',
    orderId: 'ord-sc-01',
    status: 'effective',
    title: '验收｜完整闭环服务协议',
    templateId: 'template-card-standard',
    sentAt: T,
    signedAt: T,
    effectiveAt: T,
  },
  {
    id: 'contract-sc-02',
    memberId: '1',
    orderId: 'ord-sc-02',
    status: 'pending_signature',
    title: '验收｜待签署服务协议',
    templateId: 'template-card-standard',
    sentAt: T,
  },
  {
    id: 'contract-sc-03',
    memberId: '3',
    orderId: 'ord-sc-03',
    status: 'signed',
    title: '验收｜已签署未发资产协议',
    templateId: 'template-card-standard',
    sentAt: T,
    signedAt: T,
  },
  {
    id: 'contract-sc-05',
    memberId: '3',
    orderId: 'ord-sc-05',
    status: 'effective',
    title: '验收｜积分兑换协议',
    templateId: 'template-card-standard',
    sentAt: T,
    signedAt: T,
    effectiveAt: T,
  },
  {
    id: 'contract-sc-06',
    memberId: '5',
    orderId: 'ord-sc-06',
    status: 'effective',
    title: '验收｜退款核对用协议',
    templateId: 'template-card-standard',
    sentAt: T,
    signedAt: T,
    effectiveAt: T,
  },
  {
    id: 'contract-sc-07',
    memberId: '103',
    orderId: 'ord-sc-07',
    status: 'voided',
    title: '验收｜已取消订单协议',
    templateId: 'template-card-standard',
    sentAt: T,
  },
  {
    id: 'contract-sc-08',
    memberId: '3',
    orderId: 'ord-sc-08',
    status: 'effective',
    title: '验收｜部分退款积分协议',
    templateId: 'template-card-standard',
    sentAt: T,
    signedAt: T,
    effectiveAt: T,
  },
  {
    id: 'contract-sc-09',
    memberId: '5',
    orderId: 'ord-sc-09',
    status: 'effective',
    title: '验收｜全额退款作废核对协议',
    templateId: 'template-card-standard',
    sentAt: T,
    signedAt: T,
    effectiveAt: T,
  },
  {
    id: 'contract-sc-10',
    memberId: '2',
    orderId: 'ord-sc-10',
    status: 'effective',
    title: '验收｜未绑定资产退款协议',
    templateId: 'template-card-standard',
    sentAt: T,
    signedAt: T,
    effectiveAt: T,
  },
];

export const MALL_ORDER_SCENARIO_PAYMENTS: Payment[] = [
  {
    id: 'pay-sc-01',
    orderId: 'ord-sc-01',
    memberId: '5',
    status: 'reconciled',
    amount: 11800,
    method: 'wechat',
    transactionNo: 'wx-sc-01',
    initiatedAt: T,
    paidAt: T,
    reconciledAt: T,
  },
  {
    id: 'pay-sc-02',
    orderId: 'ord-sc-02',
    memberId: '1',
    status: 'reconciled',
    amount: 12800,
    method: 'alipay',
    transactionNo: 'ali-sc-02',
    initiatedAt: T,
    paidAt: T,
    reconciledAt: T,
  },
  {
    id: 'pay-sc-03',
    orderId: 'ord-sc-03',
    memberId: '3',
    status: 'reconciled',
    amount: 8800,
    method: 'wechat',
    transactionNo: 'wx-sc-03',
    initiatedAt: T,
    paidAt: T,
    reconciledAt: T,
  },
  {
    id: 'pay-sc-05',
    orderId: 'ord-sc-05',
    memberId: '3',
    status: 'reconciled',
    amount: 500,
    method: 'wechat',
    transactionNo: 'wx-sc-05',
    initiatedAt: T,
    paidAt: T,
    reconciledAt: T,
  },
  {
    id: 'pay-sc-06',
    orderId: 'ord-sc-06',
    memberId: '5',
    status: 'reconciled',
    amount: 1999,
    method: 'card',
    transactionNo: 'card-sc-06',
    initiatedAt: T,
    paidAt: T,
    reconciledAt: T,
  },
  {
    id: 'pay-sc-07',
    orderId: 'ord-sc-07',
    memberId: '103',
    status: 'failed',
    amount: 2999,
    method: 'wechat',
    initiatedAt: T,
  },
  {
    id: 'pay-sc-08',
    orderId: 'ord-sc-08',
    memberId: '3',
    status: 'reconciled',
    amount: 800,
    method: 'wechat',
    transactionNo: 'wx-sc-08',
    initiatedAt: T,
    paidAt: T,
    reconciledAt: T,
  },
  {
    id: 'pay-sc-09',
    orderId: 'ord-sc-09',
    memberId: '5',
    status: 'reconciled',
    amount: 3500,
    method: 'alipay',
    transactionNo: 'ali-sc-09',
    initiatedAt: T,
    paidAt: T,
    reconciledAt: T,
  },
  {
    id: 'pay-sc-10',
    orderId: 'ord-sc-10',
    memberId: '2',
    status: 'reconciled',
    amount: 3000,
    method: 'wechat',
    transactionNo: 'wx-sc-10',
    initiatedAt: T,
    paidAt: T,
    reconciledAt: T,
  },
];

export const MALL_ORDER_SCENARIO_REFUNDS: Refund[] = [
  {
    id: 'refund-sc-05',
    orderId: 'ord-sc-05',
    memberId: '3',
    status: 'completed',
    amount: 100,
    paymentId: 'pay-sc-05',
    reason: '验收样本：部分积分退回',
    requestedAt: T,
    approvedAt: T,
    completedAt: T,
    refundNo: 'RF-SC-05',
    memberAssetId: 'asset-sc-05',
    refundType: 'partial_refund',
    assetHandleType: 'reduce_balance',
    requestedAmount: 100,
    approvedAmount: 100,
  },
  {
    id: 'refund-sc-06',
    orderId: 'ord-sc-06',
    memberId: '5',
    status: 'completed',
    amount: 1999,
    paymentId: 'pay-sc-06',
    reason: '验收样本：全额退款',
    requestedAt: T,
    approvedAt: T,
    completedAt: T,
    refundNo: 'RF-SC-06',
    memberAssetId: 'asset-sc-06',
    refundType: 'full_refund',
    assetHandleType: 'keep_asset',
    requestedAmount: 1999,
    approvedAmount: 1999,
  },
  {
    id: 'refund-sc-08',
    orderId: 'ord-sc-08',
    memberId: '3',
    status: 'completed',
    amount: 200,
    paymentId: 'pay-sc-08',
    reason: '验收样本：部分退回现金等价',
    requestedAt: T,
    approvedAt: T,
    completedAt: T,
    refundNo: 'RF-SC-08',
    memberAssetId: 'asset-sc-08',
    contractId: 'contract-sc-08',
    refundType: 'partial_refund',
    assetHandleType: 'reduce_balance',
    requestedAmount: 200,
    approvedAmount: 200,
  },
  {
    id: 'refund-sc-09',
    orderId: 'ord-sc-09',
    memberId: '5',
    status: 'completed',
    amount: 3500,
    paymentId: 'pay-sc-09',
    reason: '验收样本：全额退回',
    requestedAt: T,
    approvedAt: T,
    completedAt: T,
    refundNo: 'RF-SC-09',
    memberAssetId: 'asset-sc-09',
    contractId: 'contract-sc-09',
    refundType: 'full_refund',
    assetHandleType: 'void_asset',
    requestedAmount: 3500,
    approvedAmount: 3500,
  },
  {
    id: 'refund-sc-10',
    orderId: 'ord-sc-10',
    memberId: '2',
    status: 'completed',
    amount: 500,
    paymentId: 'pay-sc-10',
    reason: '验收样本：登记退款但未绑定权益记录',
    requestedAt: T,
    approvedAt: T,
    completedAt: T,
    refundNo: 'RF-SC-10',
    contractId: 'contract-sc-10',
    refundType: 'partial_refund',
    requestedAmount: 500,
    approvedAmount: 500,
  },
];

export const MALL_ORDER_SCENARIO_ASSETS: MemberAsset[] = [
  {
    id: 'asset-sc-01',
    memberId: '5',
    name: '验收｜完整闭环季卡权益',
    status: 'effective',
    sourceOrderId: 'ord-sc-01',
    contractId: 'contract-sc-01',
    productId: 'c8',
    productType: 'card',
    balanceType: 'time',
    totalAmount: 365,
    remainingAmount: 300,
    effectiveDate: T,
    expiryDate: '2027-05-10T23:59:59+08:00',
    createdAt: T,
  },
  {
    id: 'asset-sc-05',
    memberId: '3',
    name: '验收｜有退款记录积分权益',
    status: 'used_up',
    sourceOrderId: 'ord-sc-05',
    contractId: 'contract-sc-05',
    productId: 'p2',
    productType: 'point',
    balanceType: 'points',
    totalAmount: 500,
    remainingAmount: 0,
    effectiveDate: T,
    expiryDate: '2027-05-10T23:59:59+08:00',
    createdAt: T,
  },
  {
    id: 'asset-sc-06',
    memberId: '5',
    name: '验收｜退款后仍显示可用权益',
    status: 'effective',
    sourceOrderId: 'ord-sc-06',
    contractId: 'contract-sc-06',
    productId: 'c8',
    productType: 'card',
    balanceType: 'count',
    totalAmount: 10,
    remainingAmount: 10,
    effectiveDate: T,
    expiryDate: '2027-05-10T23:59:59+08:00',
    createdAt: T,
  },
  {
    id: 'asset-sc-08',
    memberId: '3',
    name: '验收｜部分退款后仍有余量积分包',
    status: 'effective',
    sourceOrderId: 'ord-sc-08',
    contractId: 'contract-sc-08',
    productId: 'p2',
    productType: 'point',
    balanceType: 'points',
    totalAmount: 800,
    remainingAmount: 600,
    effectiveDate: T,
    expiryDate: '2027-05-10T23:59:59+08:00',
    createdAt: T,
  },
  {
    id: 'asset-sc-09',
    memberId: '5',
    name: '验收｜全额退款后已作废卡项权益',
    status: 'cancelled',
    sourceOrderId: 'ord-sc-09',
    contractId: 'contract-sc-09',
    productId: 'c8',
    productType: 'card',
    balanceType: 'count',
    totalAmount: 10,
    remainingAmount: 0,
    effectiveDate: T,
    expiryDate: '2027-05-10T23:59:59+08:00',
    createdAt: T,
  },
];
