/** 规则配置模块局部 demo 数据 */

import { formatSettingsDateTime, formatSettingsPorts } from './settingsFormatters';

export type SettingsWorkbenchSegment =
  | 'booking'
  | 'courses'
  | 'cardBenefits'
  | 'contract'
  | 'points'
  | 'teacherPay'
  | 'crossStore'
  | 'notifyPerm';

export const SETTINGS_WORKBENCH_SEGMENTS: { id: SettingsWorkbenchSegment; label: string }[] = [
  { id: 'booking', label: '预约与签到' },
  { id: 'courses', label: '课程与排课' },
  { id: 'cardBenefits', label: '卡项权益' },
  { id: 'contract', label: '合同 / 退款 / 转卡 / 冻结' },
  { id: 'points', label: '积分商城' },
  { id: 'teacherPay', label: '老师课时费' },
  { id: 'crossStore', label: '跨店结算' },
  { id: 'notifyPerm', label: '通知与权限' },
];

export const SETTINGS_SEGMENT_HINTS: Record<SettingsWorkbenchSegment, string> = {
  booking: '预约窗口、取消、爽约、签到口径（三端一致）',
  courses: '开课人数、满员、候补、发布与调课',
  cardBenefits: '卡项权益、冻结、转卡、适用范围',
  contract: '合同、退款、转卡、冻结与敏感操作留痕',
  points: '积分获得、使用、过期与活动倍率',
  teacherPay: '课时费预估与结算条件（非真实发放）',
  crossStore: '跨店耗课、通馆卡与结算价',
  notifyPerm: '通知模板、可见角色与权限审计',
};

export type SettingsActionGroup = 'conflict' | 'pendingPublish' | 'missing' | 'sensitive';

export interface SettingsListFilters {
  query: string;
  status: string;
  sensitivity: string;
  port: string;
  conflictOnly: boolean;
  pendingOnly: boolean;
}

export const DEFAULT_SETTINGS_FILTERS: SettingsListFilters = {
  query: '',
  status: '全部',
  sensitivity: '全部',
  port: '全部',
  conflictOnly: false,
  pendingOnly: false,
};

export const SETTINGS_FILTER_OPTIONS = {
  statuses: ['全部', '已发布', '草稿', '待审核', '待发布', '已停用', '配置缺失', '存在冲突'],
  sensitivities: ['全部', '普通', '重要', '敏感', '高敏感'],
  ports: ['全部', '会员端', '老师端', 'PC 后台', '财务', '合同', '权限审计'],
};

export const SETTINGS_SEGMENT_COLUMNS: Record<
  SettingsWorkbenchSegment,
  { col1: string; col2: string; col3: string; col4: string; col5?: string; col6?: string }
> = {
  booking: {
    col1: '适用课程',
    col2: '适用门店',
    col3: '前台展示',
    col4: '当前状态',
    col5: '风险',
    col6: '影响端口',
  },
  courses: {
    col1: '适用课程类型',
    col2: '开课人数',
    col3: '满员规则',
    col4: '候补规则',
    col5: '发布状态',
    col6: '风险',
  },
  cardBenefits: {
    col1: '权益类型',
    col2: '有效期',
    col3: '适用范围',
    col4: '冻结规则',
    col5: '转卡规则',
    col6: '当前状态',
  },
  contract: {
    col1: '关联合同模板',
    col2: '适用产品',
    col3: '审批要求',
    col4: '财务影响',
    col5: '会员资产影响',
    col6: '当前状态',
  },
  points: {
    col1: '获得方式',
    col2: '使用方式',
    col3: '有效期',
    col4: '适用门店',
    col5: '前台展示',
    col6: '当前状态',
  },
  teacherPay: {
    col1: '适用老师类型',
    col2: '适用课程',
    col3: '计费方式',
    col4: '结算条件',
    col5: '财务状态',
    col6: '当前状态',
  },
  crossStore: {
    col1: '售卡门店',
    col2: '耗课门店',
    col3: '结算方式',
    col4: '最低结算价',
    col5: '财务影响',
    col6: '当前状态',
  },
  notifyPerm: {
    col1: '触发对象',
    col2: '通知端口',
    col3: '可见角色',
    col4: '敏感权限',
    col5: '状态',
    col6: '风险',
  },
};

export interface SettingsRuleJudgment {
  summary: string;
  stuck: string;
  nextStep: string;
}

export interface SettingsRuleRow {
  id: string;
  ruleId: string;
  ruleName: string;
  segment: SettingsWorkbenchSegment;
  ruleType: string;
  status: string;
  sensitivity: string;
  affectedPorts: string[];
  linkedModules: string[];
  applicableStores: string;
  applicableProducts: string;
  applicableCourseTypes: string;
  frontendText: string;
  backendLogic: string;
  teacherSideLogic: string;
  financeImpact: string;
  contractImpact: string;
  assetImpact: string;
  riskTags: string[];
  conflictReason: string;
  missingConfigReason: string;
  approvalRequired: string;
  editableRoles: string;
  publishStatus: string;
  updatedBy: string;
  updatedAt: string;
  nextAction: string;
  todaySuggestion: string;
  judgment: SettingsRuleJudgment;
  sync: {
    member: string;
    teacher: string;
    backend: string;
    finance: string;
    contract: string;
    audit: string;
  };
  riskChecks: string[];
  operationLogs: string[];
  /** 分段表格展示用 */
  displayCol1: string;
  displayCol2: string;
  displayCol3: string;
  displayCol4: string;
  displayRisk: string;
  /** v1.1 审查视图扩展 */
  syncAligned: boolean;
  keyImpacts: SettingsKeyImpacts;
  riskDetails: SettingsRiskDetailItem[];
  versionLogs: SettingsVersionLogEntry[];
  unconfiguredItems: string[];
  exampleNote: string;
  viewerRoles: string;
  submitterRoles: string;
  publisherRoles: string;
}

export interface SettingsKeyImpacts {
  booking: boolean;
  asset: boolean;
  finance: boolean;
  contract: boolean;
  auditRequired: boolean;
}

export interface SettingsRiskDetailItem {
  item: string;
  module: string;
  level: string;
  suggestion: string;
}

export interface SettingsVersionLogEntry {
  at: string;
  by: string;
  action: string;
  reason: string;
  publishStatus: string;
  note: string;
}

export interface SettingsMetricItem {
  id: string;
  label: string;
  value: string;
  hint: string;
  tone?: 'default' | 'amber' | 'rose';
}

export interface SettingsInsightTip {
  id: string;
  tag: string;
  line: string;
  actionLabel: string;
  actionKey: string;
}

export interface SettingsActionItem {
  id: string;
  group: SettingsActionGroup;
  /** row id 或 R-xxx 业务编号 */
  ruleId: string;
  title: string;
  statusLabel: string;
  riskLine: string;
  impactChain: string[];
  openTab?: 'overview' | 'sync' | 'risk' | 'approval';
}

export interface SettingsOperationSnapshot {
  rules: SettingsRuleRow[];
  metrics: SettingsMetricItem[];
  insights: SettingsInsightTip[];
  actionQueue: SettingsActionItem[];
}

const STORES = '万象馆 / 城西馆 / 滨江馆 / 西湖馆 / 云谷馆';
const PRODUCTS = [
  '初遇卡 Spark',
  '锦鲤卡 Flow',
  '天选卡 Prime',
  '硬核卡 Core',
  '自由卡 Flex',
  '瑜伽月卡',
  '瑜伽季卡',
  '瑜伽年卡',
  '普拉提月卡',
  '私教体验包',
  '普拉提教培早鸟名额',
];

type RuleSeed = Omit<
  SettingsRuleRow,
  | 'id'
  | 'syncAligned'
  | 'keyImpacts'
  | 'riskDetails'
  | 'versionLogs'
  | 'unconfiguredItems'
  | 'exampleNote'
  | 'viewerRoles'
  | 'submitterRoles'
  | 'publisherRoles'
>;

type RuleBase = RuleSeed & { id: string };

const mkRule = (seed: RuleSeed, index: number): RuleBase => ({
  ...seed,
  id: `set-rule-${index + 1}`,
});

const defaultJudgment = (status: string, conflict: string, missing: string): SettingsRuleJudgment => ({
  summary:
    status === '存在冲突'
      ? '规则口径在三端或财务链路存在不一致，需复核后发布'
      : status === '配置缺失'
        ? '规则项未完整配置，可能影响预约或资产处理'
        : status === '待审核' || status === '待发布'
          ? '规则已修改但未发布，前台仍使用旧版本'
          : '规则已发布，建议定期复核三端展示一致性',
  stuck: conflict !== '—' ? conflict : missing !== '—' ? missing : '—',
  nextStep:
    status === '存在冲突'
      ? '对齐会员端文案、后台计算与老师端执行后提交审核'
      : status === '待审核'
        ? '完成总部 / 财务审批后发布（前端演示）'
        : '按计划巡检，保留操作日志',
});

const buildRules = (): RuleBase[] => {
  const seeds: RuleSeed[] = [
    // booking x6
    {
      ruleId: 'R-BK-001',
      ruleName: '开课前 20 分钟停止预约',
      segment: 'booking',
      ruleType: '预约窗口',
      status: '已发布',
      sensitivity: '重要',
      affectedPorts: ['会员端', 'PC 后台'],
      linkedModules: ['预约'],
      applicableStores: STORES,
      applicableProducts: '全部课程',
      applicableCourseTypes: '团课 / 小班 / 私教',
      frontendText: '开课前 20 分钟不可预约',
      backendLogic: '当前时间 < 开课时间 - 20min 可预约',
      teacherSideLogic: '仅查看，不可代预约',
      financeImpact: '无直接财务影响',
      contractImpact: '无',
      assetImpact: '占用预约名额',
      riskTags: [],
      conflictReason: '—',
      missingConfigReason: '—',
      approvalRequired: '教务可编辑，发布需店长',
      editableRoles: '总部管理员 / 店长 / 教务',
      publishStatus: '已发布 v3.2',
      updatedBy: '教务 A',
      updatedAt: '2026-05-12 14:00',
      nextAction: '—',
      todaySuggestion: '与会员端倒计时展示一致',
      judgment: defaultJudgment('已发布', '—', '—'),
      sync: {
        member: '展示「开课前 20 分钟停止预约」',
        teacher: '课表只读，不可改预约',
        backend: '拦截超时预约并记录日志',
        finance: '不影响',
        contract: '不影响',
        audit: '预约失败需留痕',
      },
      riskChecks: ['三端文案一致', '节假日例外已配置'],
      operationLogs: ['2026-05-12 · 教务 A · 发布 v3.2'],
      displayCol1: '全部课程',
      displayCol2: STORES,
      displayCol3: '开课前 20 分钟停止预约',
      displayCol4: '已发布',
      displayRisk: '—',
    },
    {
      ruleId: 'R-BK-002',
      ruleName: '开课前 4 小时免费取消',
      segment: 'booking',
      ruleType: '取消规则',
      status: '存在冲突',
      sensitivity: '敏感',
      affectedPorts: ['会员端', 'PC 后台', '财务'],
      linkedModules: ['预约', '资产'],
      applicableStores: STORES,
      applicableProducts: '团课 / 小班',
      applicableCourseTypes: '团课 / 小班',
      frontendText: '开课前 4 小时可免费取消',
      backendLogic: '后台配置为开课前 6 小时免费取消',
      teacherSideLogic: '老师端展示 4 小时（与会员端一致）',
      financeImpact: '影响预收与耗课确认时点',
      contractImpact: '关联取消条款',
      assetImpact: '释放预约名额 / 扣点回退',
      riskTags: ['规则冲突'],
      conflictReason: '会员端显示 4 小时，后台配置 6 小时',
      missingConfigReason: '—',
      approvalRequired: '修改需总部审批',
      editableRoles: '总部管理员',
      publishStatus: '草稿待发布',
      updatedBy: '总部规则组',
      updatedAt: '2026-05-13 09:30',
      nextAction: '对齐取消窗口后发布',
      todaySuggestion: '优先处理预约取消规则冲突',
      judgment: defaultJudgment('存在冲突', '会员端与后台取消窗口不一致', '—'),
      sync: {
        member: '展示 4 小时免费取消',
        teacher: '展示 4 小时',
        backend: '按 6 小时计算是否扣费',
        finance: '取消时点影响确认收入',
        contract: '需与合同取消条款一致',
        audit: '取消操作必须留痕',
      },
      riskChecks: ['冲突：前后台取消窗口', '影响预约', '影响资产回退'],
      operationLogs: ['2026-05-13 · 总部 · 草稿保存'],
      displayCol1: '团课 / 小班',
      displayCol2: STORES,
      displayCol3: '会员端 4h / PC 后台 6h',
      displayCol4: '存在冲突',
      displayRisk: '口径不一致',
    },
    {
      ruleId: 'R-BK-003',
      ruleName: '爽约扣点 / 记录',
      segment: 'booking',
      ruleType: '爽约',
      status: '已发布',
      sensitivity: '高敏感',
      affectedPorts: ['会员端', 'PC 后台', '财务'],
      linkedModules: ['预约', '资产', '积分'],
      applicableStores: STORES,
      applicableProducts: '点数卡 / 期限卡',
      applicableCourseTypes: '团课 / 小班',
      frontendText: '未取消且未到课记为爽约，按规则扣点',
      backendLogic: '完课时间后自动标记爽约并扣点',
      teacherSideLogic: '老师扫码未到课触发爽约核对',
      financeImpact: '影响耗课与确认收入时点',
      contractImpact: '关联会员协议',
      assetImpact: '扣减权益 / 记爽约次数',
      riskTags: [],
      conflictReason: '—',
      missingConfigReason: '—',
      approvalRequired: '总部 + 财务知悉',
      editableRoles: '总部管理员',
      publishStatus: '已发布 v2.8',
      updatedBy: '财务 B',
      updatedAt: '2026-05-01 11:00',
      nextAction: '—',
      todaySuggestion: '爽约与积分规则联动需复核',
      judgment: defaultJudgment('已发布', '—', '—'),
      sync: {
        member: '爽约提醒 + 扣点说明',
        teacher: '签到核销，不可代签到',
        backend: '标记爽约，不代签到',
        finance: '耗课后确认收入',
        contract: '协议条款外显',
        audit: '爽约必须留痕',
      },
      riskChecks: ['影响资产', '影响财务确认'],
      operationLogs: ['2026-05-01 · 财务 B · 发布'],
      displayCol1: '团课 / 小班',
      displayCol2: STORES,
      displayCol3: '爽约扣点',
      displayCol4: '已发布',
      displayRisk: '—',
    },
    {
      ruleId: 'R-BK-004',
      ruleName: '会员端不可主动扫码签到',
      segment: 'booking',
      ruleType: '签到',
      status: '已发布',
      sensitivity: '重要',
      affectedPorts: ['会员端', '老师端'],
      linkedModules: ['签到'],
      applicableStores: STORES,
      applicableProducts: '全部',
      applicableCourseTypes: '全部',
      frontendText: '会员端不提供扫码签到入口',
      backendLogic: '仅老师端 METeach 扫码核销',
      teacherSideLogic: '老师扫码核销到课',
      financeImpact: '影响耗课触发',
      contractImpact: '无',
      assetImpact: '到课才扣权益',
      riskTags: [],
      conflictReason: '—',
      missingConfigReason: '—',
      approvalRequired: '教务发布',
      editableRoles: '总部 / 店长 / 教务',
      publishStatus: '已发布',
      updatedBy: '教务 A',
      updatedAt: '2026-04-20 16:00',
      nextAction: '—',
      todaySuggestion: '后台不代签到',
      judgment: defaultJudgment('已发布', '—', '—'),
      sync: {
        member: '不可扫码签到',
        teacher: '扫码核销',
        backend: '只记录，不代签到',
        finance: '签到后耗课',
        contract: '无',
        audit: '签到变更留痕',
      },
      riskChecks: ['老师端执行口径'],
      operationLogs: ['2026-04-20 · 发布'],
      displayCol1: '全部课程',
      displayCol2: STORES,
      displayCol3: '老师端扫码',
      displayCol4: '已发布',
      displayRisk: '—',
    },
    {
      ruleId: 'R-BK-005',
      ruleName: '候补队列自动递补',
      segment: 'booking',
      ruleType: '候补',
      status: '配置缺失',
      sensitivity: '重要',
      affectedPorts: ['会员端', 'PC 后台'],
      linkedModules: ['预约', '通知'],
      applicableStores: STORES,
      applicableProducts: '热门团课',
      applicableCourseTypes: '团课',
      frontendText: '—',
      backendLogic: '候补成功后通知模板未配置完整',
      teacherSideLogic: '—',
      financeImpact: '无',
      contractImpact: '无',
      assetImpact: '占用候补名额',
      riskTags: ['缺失配置'],
      conflictReason: '—',
      missingConfigReason: '候补成功通知模板缺失',
      approvalRequired: '教务 + 总部',
      editableRoles: '总部 / 教务',
      publishStatus: '未发布',
      updatedBy: '—',
      updatedAt: '—',
      nextAction: '补全通知模板',
      todaySuggestion: '补全候补通知配置',
      judgment: defaultJudgment('配置缺失', '—', '候补通知未配置'),
      sync: {
        member: '展示候补中，成功通知缺失',
        teacher: '无',
        backend: '递补逻辑有，通知缺失',
        finance: '无',
        contract: '无',
        audit: '递补需留痕',
      },
      riskChecks: ['缺失：通知模板', '影响预约体验'],
      operationLogs: [],
      displayCol1: '团课',
      displayCol2: STORES,
      displayCol3: '未配置',
      displayCol4: '配置缺失',
      displayRisk: '通知缺失',
    },
    {
      ruleId: 'R-BK-006',
      ruleName: '后台不直接代签到',
      segment: 'booking',
      ruleType: '签到',
      status: '已发布',
      sensitivity: '敏感',
      affectedPorts: ['PC 后台', '权限审计'],
      linkedModules: ['签到', '权限'],
      applicableStores: STORES,
      applicableProducts: '全部',
      applicableCourseTypes: '全部',
      frontendText: '—',
      backendLogic: '后台仅「需核对」展示，不提供代签到按钮',
      teacherSideLogic: '—',
      financeImpact: '防止异常耗课',
      contractImpact: '无',
      assetImpact: '防止异常扣权益',
      riskTags: [],
      conflictReason: '—',
      missingConfigReason: '—',
      approvalRequired: '总部锁定',
      editableRoles: '总部管理员',
      publishStatus: '已发布',
      updatedBy: '总部',
      updatedAt: '2026-03-01 10:00',
      nextAction: '—',
      todaySuggestion: '保持权限边界',
      judgment: defaultJudgment('已发布', '—', '—'),
      sync: {
        member: '—',
        teacher: '正常核销',
        backend: '只核对不代操作',
        finance: '避免异常收入',
        contract: '无',
        audit: '敏感权限',
      },
      riskChecks: ['权限边界'],
      operationLogs: ['2026-03-01 · 锁定规则'],
      displayCol1: '全部',
      displayCol2: STORES,
      displayCol3: '仅核对',
      displayCol4: '已发布',
      displayRisk: '—',
    },
    // courses x5
    {
      ruleId: 'R-CR-001',
      ruleName: '团课最低开课人数',
      segment: 'courses',
      ruleType: '开课',
      status: '已发布',
      sensitivity: '重要',
      affectedPorts: ['会员端', 'PC 后台', '老师端'],
      linkedModules: ['排课'],
      applicableStores: STORES,
      applicableProducts: '—',
      applicableCourseTypes: '团课',
      frontendText: '未满最低人数将取消并通知',
      backendLogic: '开课前 2h 检查预约人数 < 最低人数则取消',
      teacherSideLogic: '课表显示是否成课',
      financeImpact: '无',
      contractImpact: '无',
      assetImpact: '释放预约',
      riskTags: [],
      conflictReason: '—',
      missingConfigReason: '—',
      approvalRequired: '教务发布',
      editableRoles: '总部 / 店长 / 教务',
      publishStatus: '已发布',
      updatedBy: '教务 B',
      updatedAt: '2026-05-10 15:00',
      nextAction: '—',
      todaySuggestion: '—',
      judgment: defaultJudgment('已发布', '—', '—'),
      sync: {
        member: '未成课自动取消通知',
        teacher: '课表状态更新',
        backend: '自动取消排课',
        finance: '无',
        contract: '无',
        audit: '取消留痕',
      },
      riskChecks: [],
      operationLogs: ['2026-05-10 · 发布'],
      displayCol1: '团课',
      displayCol2: '最低 3 人',
      displayCol3: '未满则取消',
      displayCol4: '已发布',
      displayRisk: '—',
    },
    {
      ruleId: 'R-CR-002',
      ruleName: '小班容量上限',
      segment: 'courses',
      ruleType: '容量',
      status: '已发布',
      sensitivity: '普通',
      affectedPorts: ['会员端', 'PC 后台'],
      linkedModules: ['排课', '预约'],
      applicableStores: STORES,
      applicableProducts: '—',
      applicableCourseTypes: '小班',
      frontendText: '小班满员后进入候补',
      backendLogic: '容量 = 教室床位 - 教练位',
      teacherSideLogic: '查看预约人数',
      financeImpact: '无',
      contractImpact: '无',
      assetImpact: '—',
      riskTags: [],
      conflictReason: '—',
      missingConfigReason: '—',
      approvalRequired: '教务',
      editableRoles: '教务 / 店长',
      publishStatus: '已发布',
      updatedBy: '教务 A',
      updatedAt: '2026-04-15 11:00',
      nextAction: '—',
      todaySuggestion: '—',
      judgment: defaultJudgment('已发布', '—', '—'),
      sync: {
        member: '满员候补',
        teacher: '只读',
        backend: '控制容量',
        finance: '无',
        contract: '无',
        audit: '—',
      },
      riskChecks: [],
      operationLogs: [],
      displayCol1: '小班',
      displayCol2: '按教室',
      displayCol3: '满员候补',
      displayCol4: '已发布',
      displayRisk: '—',
    },
    {
      ruleId: 'R-CR-003',
      ruleName: '私教预约窗口 7 天',
      segment: 'courses',
      ruleType: '私教',
      status: '待审核',
      sensitivity: '重要',
      affectedPorts: ['会员端', 'PC 后台'],
      linkedModules: ['预约'],
      applicableStores: STORES,
      applicableProducts: '私教课包',
      applicableCourseTypes: '私教',
      frontendText: '可预约未来 7 天内私教',
      backendLogic: '拟改为 14 天，待审核',
      teacherSideLogic: '课表同步',
      financeImpact: '无',
      contractImpact: '无',
      assetImpact: '—',
      riskTags: ['待审核'],
      conflictReason: '—',
      missingConfigReason: '—',
      approvalRequired: '总部审批',
      editableRoles: '总部 / 店长',
      publishStatus: '待发布',
      updatedBy: '店长 王凯',
      updatedAt: '2026-05-14 10:00',
      nextAction: '待总部审核发布',
      todaySuggestion: '审核私教预约窗口变更',
      judgment: defaultJudgment('待审核', '—', '—'),
      sync: {
        member: '当前 7 天',
        teacher: '7 天课表',
        backend: '拟 14 天',
        finance: '无',
        contract: '无',
        audit: '变更留痕',
      },
      riskChecks: ['待审核发布'],
      operationLogs: ['2026-05-14 · 草稿'],
      displayCol1: '私教',
      displayCol2: '7 天 → 14 天',
      displayCol3: '待审核',
      displayCol4: '待审核',
      displayRisk: '待发布',
    },
    {
      ruleId: 'R-CR-004',
      ruleName: '课程发布需教务审核',
      segment: 'courses',
      ruleType: '发布',
      status: '已发布',
      sensitivity: '重要',
      affectedPorts: ['PC 后台', '老师端'],
      linkedModules: ['排课'],
      applicableStores: STORES,
      applicableProducts: '—',
      applicableCourseTypes: '全部',
      frontendText: '—',
      backendLogic: '店长提交 → 教务审核 → 前台可见',
      teacherSideLogic: '审核通过后课表可见',
      financeImpact: '无',
      contractImpact: '无',
      assetImpact: '—',
      riskTags: [],
      conflictReason: '—',
      missingConfigReason: '—',
      approvalRequired: '教务审核',
      editableRoles: '店长 / 教务 / 总部',
      publishStatus: '已发布',
      updatedBy: '总部',
      updatedAt: '2026-02-01 09:00',
      nextAction: '—',
      todaySuggestion: '—',
      judgment: defaultJudgment('已发布', '—', '—'),
      sync: {
        member: '仅见已发布课',
        teacher: '见已发布',
        backend: '审核流',
        finance: '无',
        contract: '无',
        audit: '发布留痕',
      },
      riskChecks: [],
      operationLogs: [],
      displayCol1: '全部类型',
      displayCol2: '教务审核',
      displayCol3: '—',
      displayCol4: '已发布',
      displayRisk: '—',
    },
    {
      ruleId: 'R-CR-005',
      ruleName: '代课需审批',
      segment: 'courses',
      ruleType: '代课',
      status: '已发布',
      sensitivity: '敏感',
      affectedPorts: ['老师端', 'PC 后台'],
      linkedModules: ['排课', '课时费'],
      applicableStores: STORES,
      applicableProducts: '—',
      applicableCourseTypes: '全部',
      frontendText: '—',
      backendLogic: '代课申请 → 店长审批 → 课表更新',
      teacherSideLogic: '代课老师收到课表变更',
      financeImpact: '影响课时费归属',
      contractImpact: '无',
      assetImpact: '—',
      riskTags: [],
      conflictReason: '—',
      missingConfigReason: '—',
      approvalRequired: '店长审批',
      editableRoles: '店长 / 教务',
      publishStatus: '已发布',
      updatedBy: '教务 A',
      updatedAt: '2026-04-01 14:00',
      nextAction: '—',
      todaySuggestion: '—',
      judgment: defaultJudgment('已发布', '—', '—'),
      sync: {
        member: '通知老师变更（如有）',
        teacher: '代课提醒',
        backend: '审批记录',
        finance: '课时费待核',
        contract: '无',
        audit: '必须留痕',
      },
      riskChecks: ['影响老师收入'],
      operationLogs: [],
      displayCol1: '全部',
      displayCol2: '店长审批',
      displayCol3: '—',
      displayCol4: '已发布',
      displayRisk: '—',
    },
    {
      ruleId: 'R-CR-006',
      ruleName: '调课 / 取消需留痕',
      segment: 'courses',
      ruleType: '调课',
      status: '已发布',
      sensitivity: '敏感',
      affectedPorts: ['PC 后台', '权限审计'],
      linkedModules: ['排课'],
      applicableStores: STORES,
      applicableProducts: '—',
      applicableCourseTypes: '全部',
      frontendText: '—',
      backendLogic: '所有调课取消写入操作日志',
      teacherSideLogic: '—',
      financeImpact: '间接',
      contractImpact: '无',
      assetImpact: '—',
      riskTags: [],
      conflictReason: '—',
      missingConfigReason: '—',
      approvalRequired: '—',
      editableRoles: '总部',
      publishStatus: '已发布',
      updatedBy: '总部',
      updatedAt: '2026-01-10 10:00',
      nextAction: '—',
      todaySuggestion: '—',
      judgment: defaultJudgment('已发布', '—', '—'),
      sync: {
        member: '收到变更通知',
        teacher: '课表更新',
        backend: '强制留痕',
        finance: '—',
        contract: '无',
        audit: '必需',
      },
      riskChecks: [],
      operationLogs: [],
      displayCol1: '全部',
      displayCol2: '强制留痕',
      displayCol3: '—',
      displayCol4: '已发布',
      displayRisk: '—',
    },
  ];

  // Add card benefits - one per product + extras
  PRODUCTS.forEach((product, i) => {
    const frozen = product.includes('Flow') || product.includes('Prime') ? '已配置' : i % 3 === 0 ? '配置缺失' : '已配置';
    const status = frozen === '配置缺失' ? '配置缺失' : '已发布';
    seeds.push({
      ruleId: `R-CB-${String(i + 1).padStart(3, '0')}`,
      ruleName: `${product} · 权益与冻结`,
      segment: 'cardBenefits',
      ruleType: '卡项权益',
      status,
      sensitivity: product.includes('教培') ? '高敏感' : '敏感',
      affectedPorts: ['会员端', 'PC 后台', '财务'],
      linkedModules: ['资产', '合同'],
      applicableStores: product.includes('Flex') ? '全馆通' : STORES,
      applicableProducts: product,
      applicableCourseTypes: product.includes('私教') ? '私教' : product.includes('普拉提') ? '普拉提' : '瑜伽',
      frontendText: `${product} 权益说明外显`,
      backendLogic: '有效期、适用范围、扣点规则',
      teacherSideLogic: '—',
      financeImpact: '影响预收负债',
      contractImpact: '关联合同模板',
      assetImpact: '生成会员资产',
      riskTags: frozen === '配置缺失' ? ['冻结未配置'] : [],
      conflictReason: '—',
      missingConfigReason: frozen === '配置缺失' ? '冻结上限未配置' : '—',
      approvalRequired: '总部 + 财务',
      editableRoles: '总部 / 财务',
      publishStatus: status === '已发布' ? '已发布' : '草稿',
      updatedBy: '财务 A',
      updatedAt: '2026-05-08 10:00',
      nextAction: frozen === '配置缺失' ? '补全冻结规则' : '—',
      todaySuggestion: frozen === '配置缺失' ? '冻结规则缺失' : '—',
      judgment: defaultJudgment(status, '—', frozen === '配置缺失' ? '冻结未配置' : '—'),
      sync: {
        member: '看到权益与有效期',
        teacher: '仅练习画像',
        backend: '资产生成规则',
        finance: '预收负债',
        contract: '合同条款',
        audit: '资产变更留痕',
      },
      riskChecks: frozen === '配置缺失' ? ['缺失：冻结上限'] : ['权益一致'],
      operationLogs: ['2026-05-08 · 配置'],
      displayCol1: product,
      displayCol2: '期限 / 点数',
      displayCol3: frozen === '配置缺失' ? '冻结未配置' : '冻结 30 天',
      displayCol4: status,
      displayRisk: frozen === '配置缺失' ? '冻结缺失' : '—',
    });
  });

  // contract, points, teacherPay, crossStore, notifyPerm - add programmatic batches
  const moreSeeds: RuleSeed[] = [
    {
      ruleId: 'R-CT-001',
      ruleName: '退款需审批',
      segment: 'contract',
      ruleType: '退款',
      status: '已发布',
      sensitivity: '高敏感',
      affectedPorts: ['PC 后台', '财务', '合同'],
      linkedModules: ['退款', '资产'],
      applicableStores: STORES,
      applicableProducts: '全部卡项',
      applicableCourseTypes: '—',
      frontendText: '退款提交后需审批',
      backendLogic: '店长 / 财务分级审批',
      teacherSideLogic: '不可见退款金额',
      financeImpact: '待财务复核',
      contractImpact: '合同退款条款',
      assetImpact: '扣减 / 作废权益',
      riskTags: ['敏感规则'],
      conflictReason: '—',
      missingConfigReason: '—',
      approvalRequired: '总部 + 财务',
      editableRoles: '总部 / 财务 / 店长',
      publishStatus: '已发布',
      updatedBy: '财务 B',
      updatedAt: '2026-05-01 09:00',
      nextAction: '—',
      todaySuggestion: '敏感操作留痕',
      judgment: defaultJudgment('已发布', '—', '—'),
      sync: {
        member: '可见进度，不见财务细节',
        teacher: '不可见',
        backend: '审批流',
        finance: '待财务复核',
        contract: '条款绑定',
        audit: '必需',
      },
      riskChecks: ['影响财务', '影响资产'],
      operationLogs: ['2026-05-01 · 发布'],
      displayCol1: '退款审批',
      displayCol2: '全部合同模板',
      displayCol3: '分级审批',
      displayCol4: '已发布',
      displayRisk: '高敏感',
    },
    {
      ruleId: 'R-CT-002',
      ruleName: '部分退款需核对剩余权益',
      segment: 'contract',
      ruleType: '退款',
      status: '已发布',
      sensitivity: '高敏感',
      affectedPorts: ['PC 后台', '财务'],
      linkedModules: ['退款', '资产'],
      applicableStores: STORES,
      applicableProducts: '课包 / 私教',
      applicableCourseTypes: '—',
      frontendText: '—',
      backendLogic: '按未耗课比例计算可退额',
      teacherSideLogic: '—',
      financeImpact: '待财务复核',
      contractImpact: '是',
      assetImpact: '扣减剩余权益',
      riskTags: [],
      conflictReason: '—',
      missingConfigReason: '—',
      approvalRequired: '财务确认',
      editableRoles: '财务 / 总部',
      publishStatus: '已发布',
      updatedBy: '财务 B',
      updatedAt: '2026-04-20 14:00',
      nextAction: '—',
      todaySuggestion: '—',
      judgment: defaultJudgment('已发布', '—', '—'),
      sync: {
        member: '展示申请额',
        teacher: '—',
        backend: '计算可退额',
        finance: '复核后处理',
        contract: '绑定',
        audit: '必需',
      },
      riskChecks: [],
      operationLogs: [],
      displayCol1: '部分退款',
      displayCol2: '私教课包',
      displayCol3: '核对权益',
      displayCol4: '已发布',
      displayRisk: '—',
    },
    {
      ruleId: 'R-CT-003',
      ruleName: '转卡需手续费和店长审批',
      segment: 'contract',
      ruleType: '转卡',
      status: '待审核',
      sensitivity: '高敏感',
      affectedPorts: ['PC 后台', '财务'],
      linkedModules: ['转卡', '资产'],
      applicableStores: STORES,
      applicableProducts: '可转卡项',
      applicableCourseTypes: '—',
      frontendText: '转卡手续费外显',
      backendLogic: '手续费率 5%，待发布',
      teacherSideLogic: '—',
      financeImpact: '影响收入确认',
      contractImpact: '转卡协议',
      assetImpact: '权益转移',
      riskTags: ['待审核'],
      conflictReason: '—',
      missingConfigReason: '—',
      approvalRequired: '总部',
      editableRoles: '总部 / 财务',
      publishStatus: '待发布',
      updatedBy: '总部规则组',
      updatedAt: '2026-05-14 11:00',
      nextAction: '待总部发布',
      todaySuggestion: '转卡规则待审',
      judgment: defaultJudgment('待审核', '—', '—'),
      sync: {
        member: '手续费说明',
        teacher: '—',
        backend: '审批 + 资产转移',
        finance: '待复核',
        contract: '转卡条款',
        audit: '必需',
      },
      riskChecks: ['待审核'],
      operationLogs: [],
      displayCol1: '转卡',
      displayCol2: '可转产品',
      displayCol3: '5% 手续费',
      displayCol4: '待审核',
      displayRisk: '待发布',
    },
    {
      ruleId: 'R-CT-004',
      ruleName: '冻结需原因、天数和有效期处理',
      segment: 'contract',
      ruleType: '冻结',
      status: '配置缺失',
      sensitivity: '敏感',
      affectedPorts: ['PC 后台', '会员端'],
      linkedModules: ['资产', '冻结'],
      applicableStores: STORES,
      applicableProducts: '锦鲤卡 Flow',
      applicableCourseTypes: '—',
      frontendText: '—',
      backendLogic: '冻结天数上限未统一',
      teacherSideLogic: '—',
      financeImpact: '延长预收负债',
      contractImpact: '冻结条款',
      assetImpact: '暂停扣点',
      riskTags: ['缺失配置'],
      conflictReason: '—',
      missingConfigReason: '部分卡项未配置冻结上限',
      approvalRequired: '店长 + 总部',
      editableRoles: '总部 / 店长',
      publishStatus: '未发布',
      updatedBy: '—',
      updatedAt: '—',
      nextAction: '补全冻结规则',
      todaySuggestion: '卡项冻结缺失优先处理',
      judgment: defaultJudgment('配置缺失', '—', '冻结上限缺失'),
      sync: {
        member: '冻结说明不完整',
        teacher: '—',
        backend: '手工处理',
        finance: '负债时点',
        contract: '需外显',
        audit: '必需',
      },
      riskChecks: ['缺失', '影响资产'],
      operationLogs: [],
      displayCol1: '冻结',
      displayCol2: '锦鲤卡 Flow',
      displayCol3: '未配置上限',
      displayCol4: '配置缺失',
      displayRisk: '冻结缺失',
    },
    {
      ruleId: 'R-CT-005',
      ruleName: '合同条款需前台外显',
      segment: 'contract',
      ruleType: '合同',
      status: '已发布',
      sensitivity: '重要',
      affectedPorts: ['会员端', 'PC 后台', '合同'],
      linkedModules: ['合同'],
      applicableStores: STORES,
      applicableProducts: '全部',
      applicableCourseTypes: '—',
      frontendText: '签署前展示完整条款',
      backendLogic: '未签署不可生成资产',
      teacherSideLogic: '—',
      financeImpact: '—',
      contractImpact: '强制外显',
      assetImpact: '签署后生成资产',
      riskTags: [],
      conflictReason: '—',
      missingConfigReason: '—',
      approvalRequired: '法务 / 总部',
      editableRoles: '总部',
      publishStatus: '已发布',
      updatedBy: '总部法务',
      updatedAt: '2026-03-15 10:00',
      nextAction: '—',
      todaySuggestion: '—',
      judgment: defaultJudgment('已发布', '—', '—'),
      sync: {
        member: '签署前可见',
        teacher: '—',
        backend: '合同状态',
        finance: '—',
        contract: '绑定',
        audit: '签署留痕',
      },
      riskChecks: [],
      operationLogs: [],
      displayCol1: '合同外显',
      displayCol2: '全部模板',
      displayCol3: '签署后生效',
      displayCol4: '已发布',
      displayRisk: '—',
    },
    {
      ruleId: 'R-PT-001',
      ruleName: '到课积分',
      segment: 'points',
      ruleType: '积分获得',
      status: '已发布',
      sensitivity: '普通',
      affectedPorts: ['会员端', 'PC 后台'],
      linkedModules: ['积分', '签到'],
      applicableStores: STORES,
      applicableProducts: '—',
      applicableCourseTypes: '全部',
      frontendText: '到课获得积分',
      backendLogic: '完课 + 签到后发放',
      teacherSideLogic: '—',
      financeImpact: '营销成本',
      contractImpact: '无',
      assetImpact: '—',
      riskTags: [],
      conflictReason: '—',
      missingConfigReason: '—',
      approvalRequired: '总部市场',
      editableRoles: '总部 / 市场',
      publishStatus: '已发布',
      updatedBy: '市场',
      updatedAt: '2026-04-01 10:00',
      nextAction: '—',
      todaySuggestion: '—',
      judgment: defaultJudgment('已发布', '—', '—'),
      sync: {
        member: '积分到账提醒',
        teacher: '—',
        backend: '自动发放',
        finance: '营销费用',
        contract: '无',
        audit: '发放留痕',
      },
      riskChecks: [],
      operationLogs: [],
      displayCol1: '到课积分',
      displayCol2: '自动发放',
      displayCol3: STORES,
      displayCol4: '已发布',
      displayRisk: '—',
    },
    {
      ruleId: 'R-PT-002',
      ruleName: '积分过期 12 个月',
      segment: 'points',
      ruleType: '有效期',
      status: '已发布',
      sensitivity: '重要',
      affectedPorts: ['会员端'],
      linkedModules: ['积分'],
      applicableStores: STORES,
      applicableProducts: '—',
      applicableCourseTypes: '—',
      frontendText: '积分 12 个月有效',
      backendLogic: '滚动过期',
      teacherSideLogic: '—',
      financeImpact: '—',
      contractImpact: '会员协议',
      assetImpact: '—',
      riskTags: [],
      conflictReason: '—',
      missingConfigReason: '—',
      approvalRequired: '总部',
      editableRoles: '总部',
      publishStatus: '已发布',
      updatedBy: '总部',
      updatedAt: '2026-02-10 09:00',
      nextAction: '—',
      todaySuggestion: '—',
      judgment: defaultJudgment('已发布', '—', '—'),
      sync: {
        member: '展示有效期',
        teacher: '—',
        backend: '定时任务',
        finance: '—',
        contract: '协议',
        audit: '—',
      },
      riskChecks: [],
      operationLogs: [],
      displayCol1: '过期规则',
      displayCol2: '12 个月',
      displayCol3: STORES,
      displayCol4: '已发布',
      displayRisk: '—',
    },
    {
      ruleId: 'R-PT-003',
      ruleName: '退款后积分回收',
      segment: 'points',
      ruleType: '回收',
      status: '已发布',
      sensitivity: '敏感',
      affectedPorts: ['PC 后台', '财务'],
      linkedModules: ['积分', '退款'],
      applicableStores: STORES,
      applicableProducts: '—',
      applicableCourseTypes: '—',
      frontendText: '—',
      backendLogic: '退款完成触发积分扣回',
      teacherSideLogic: '—',
      financeImpact: '调整营销成本',
      contractImpact: '退款条款',
      assetImpact: '—',
      riskTags: [],
      conflictReason: '—',
      missingConfigReason: '—',
      approvalRequired: '财务',
      editableRoles: '财务 / 总部',
      publishStatus: '已发布',
      updatedBy: '财务 A',
      updatedAt: '2026-03-20 15:00',
      nextAction: '—',
      todaySuggestion: '—',
      judgment: defaultJudgment('已发布', '—', '—'),
      sync: {
        member: '积分变动通知',
        teacher: '—',
        backend: '自动扣回',
        finance: '复核',
        contract: '绑定',
        audit: '必需',
      },
      riskChecks: [],
      operationLogs: [],
      displayCol1: '退款回收',
      displayCol2: '自动扣回',
      displayCol3: STORES,
      displayCol4: '已发布',
      displayRisk: '—',
    },
    {
      ruleId: 'R-PT-004',
      ruleName: '活动积分倍率',
      segment: 'points',
      ruleType: '活动',
      status: '草稿',
      sensitivity: '普通',
      affectedPorts: ['会员端'],
      linkedModules: ['积分', '营销'],
      applicableStores: '万象馆',
      applicableProducts: '—',
      applicableCourseTypes: '—',
      frontendText: '五一 2 倍积分',
      backendLogic: '活动期间倍率 2x',
      teacherSideLogic: '—',
      financeImpact: '营销预算',
      contractImpact: '无',
      assetImpact: '—',
      riskTags: [],
      conflictReason: '—',
      missingConfigReason: '—',
      approvalRequired: '市场 + 总部',
      editableRoles: '市场 / 总部',
      publishStatus: '草稿',
      updatedBy: '市场',
      updatedAt: '2026-05-14 16:00',
      nextAction: '活动前发布',
      todaySuggestion: '活动规则待发布',
      judgment: defaultJudgment('草稿', '—', '—'),
      sync: {
        member: '活动页展示',
        teacher: '—',
        backend: '活动引擎',
        finance: '费用预估',
        contract: '无',
        audit: '—',
      },
      riskChecks: [],
      operationLogs: [],
      displayCol1: '活动倍率',
      displayCol2: '2x',
      displayCol3: '万象馆',
      displayCol4: '草稿',
      displayRisk: '—',
    },
    {
      ruleId: 'R-PT-005',
      ruleName: '兑换限制（每月上限）',
      segment: 'points',
      ruleType: '使用',
      status: '已发布',
      sensitivity: '重要',
      affectedPorts: ['会员端', 'PC 后台'],
      linkedModules: ['积分', '商城'],
      applicableStores: STORES,
      applicableProducts: '积分商城',
      applicableCourseTypes: '—',
      frontendText: '每月兑换上限说明',
      backendLogic: '每月最多兑换 3 次',
      teacherSideLogic: '—',
      financeImpact: '—',
      contractImpact: '无',
      assetImpact: '—',
      riskTags: [],
      conflictReason: '—',
      missingConfigReason: '—',
      approvalRequired: '总部',
      editableRoles: '总部 / 市场',
      publishStatus: '已发布',
      updatedBy: '总部',
      updatedAt: '2026-01-20 10:00',
      nextAction: '—',
      todaySuggestion: '—',
      judgment: defaultJudgment('已发布', '—', '—'),
      sync: {
        member: '兑换页展示',
        teacher: '—',
        backend: '拦截超限',
        finance: '—',
        contract: '无',
        audit: '兑换留痕',
      },
      riskChecks: [],
      operationLogs: [],
      displayCol1: '兑换限制',
      displayCol2: '3 次 / 月',
      displayCol3: STORES,
      displayCol4: '已发布',
      displayRisk: '—',
    },
    {
      ruleId: 'R-TP-001',
      ruleName: '团课课时费',
      segment: 'teacherPay',
      ruleType: '团课',
      status: '待审核',
      sensitivity: '高敏感',
      affectedPorts: ['PC 后台', '财务', '老师端'],
      linkedModules: ['课时费'],
      applicableStores: STORES,
      applicableProducts: '—',
      applicableCourseTypes: '团课',
      frontendText: '—',
      backendLogic: '拟调整单价，待财务复核',
      teacherSideLogic: '收入预估摘要',
      financeImpact: '待财务复核',
      contractImpact: '无',
      assetImpact: '—',
      riskTags: ['待审核'],
      conflictReason: '—',
      missingConfigReason: '—',
      approvalRequired: '财务 + 总部',
      editableRoles: '财务 / 总部',
      publishStatus: '待发布',
      updatedBy: '财务 B',
      updatedAt: '2026-05-13 17:00',
      nextAction: '财务复核后发布',
      todaySuggestion: '课时费规则修改未发布',
      judgment: defaultJudgment('待审核', '—', '—'),
      sync: {
        member: '—',
        teacher: '预估摘要',
        backend: '待核计算',
        finance: '待财务复核',
        contract: '无',
        audit: '必需',
      },
      riskChecks: ['影响老师收入', '待审核'],
      operationLogs: ['2026-05-13 · 草稿'],
      displayCol1: '团课课时费',
      displayCol2: '全职 / 兼职',
      displayCol3: '按节计费',
      displayCol4: '待审核',
      displayRisk: '待财务复核',
    },
    {
      ruleId: 'R-TP-002',
      ruleName: '小班课时费',
      segment: 'teacherPay',
      ruleType: '小班',
      status: '已发布',
      sensitivity: '敏感',
      affectedPorts: ['财务', '老师端'],
      linkedModules: ['课时费'],
      applicableStores: STORES,
      applicableProducts: '—',
      applicableCourseTypes: '小班',
      frontendText: '—',
      backendLogic: '完课后进入待核',
      teacherSideLogic: '预估可见',
      financeImpact: '待核 / 已确认',
      contractImpact: '无',
      assetImpact: '—',
      riskTags: [],
      conflictReason: '—',
      missingConfigReason: '—',
      approvalRequired: '财务',
      editableRoles: '财务 / 总部',
      publishStatus: '已发布',
      updatedBy: '财务 B',
      updatedAt: '2026-04-10 11:00',
      nextAction: '—',
      todaySuggestion: '—',
      judgment: defaultJudgment('已发布', '—', '—'),
      sync: {
        member: '—',
        teacher: '完课后预估',
        backend: '待核列表',
        finance: '待财务复核',
        contract: '无',
        audit: '必需',
      },
      riskChecks: [],
      operationLogs: [],
      displayCol1: '小班',
      displayCol2: '完课结算',
      displayCol3: '待核',
      displayCol4: '已发布',
      displayRisk: '—',
    },
    {
      ruleId: 'R-TP-003',
      ruleName: '私教分成',
      segment: 'teacherPay',
      ruleType: '私教',
      status: '已发布',
      sensitivity: '高敏感',
      affectedPorts: ['财务', '老师端'],
      linkedModules: ['课时费'],
      applicableStores: STORES,
      applicableProducts: '私教课包',
      applicableCourseTypes: '私教',
      frontendText: '—',
      backendLogic: '按耗课金额分成 40%',
      teacherSideLogic: '预估摘要',
      financeImpact: '待财务复核',
      contractImpact: '无',
      assetImpact: '—',
      riskTags: [],
      conflictReason: '—',
      missingConfigReason: '—',
      approvalRequired: '财务',
      editableRoles: '财务 / 总部',
      publishStatus: '已发布',
      updatedBy: '财务 B',
      updatedAt: '2026-03-01 10:00',
      nextAction: '—',
      todaySuggestion: '—',
      judgment: defaultJudgment('已发布', '—', '—'),
      sync: {
        member: '—',
        teacher: '分成预估',
        backend: '耗课触发',
        finance: '确认收入后分成',
        contract: '无',
        audit: '必需',
      },
      riskChecks: [],
      operationLogs: [],
      displayCol1: '私教',
      displayCol2: '40% 分成',
      displayCol3: '耗课后',
      displayCol4: '已发布',
      displayRisk: '—',
    },
    {
      ruleId: 'R-TP-004',
      ruleName: '代课课时费',
      segment: 'teacherPay',
      ruleType: '代课',
      status: '已发布',
      sensitivity: '敏感',
      affectedPorts: ['老师端', 'PC 后台', '财务'],
      linkedModules: ['课时费', '排课'],
      applicableStores: STORES,
      applicableProducts: '—',
      applicableCourseTypes: '全部',
      frontendText: '—',
      backendLogic: '代课按原老师 80% 结算给代课老师',
      teacherSideLogic: '代课课表 + 预估',
      financeImpact: '待核',
      contractImpact: '无',
      assetImpact: '—',
      riskTags: [],
      conflictReason: '—',
      missingConfigReason: '—',
      approvalRequired: '店长 + 财务',
      editableRoles: '教务 / 财务',
      publishStatus: '已发布',
      updatedBy: '教务 A',
      updatedAt: '2026-02-20 14:00',
      nextAction: '—',
      todaySuggestion: '—',
      judgment: defaultJudgment('已发布', '—', '—'),
      sync: {
        member: '—',
        teacher: '代课费预估',
        backend: '代课审批后计算',
        finance: '待核',
        contract: '无',
        audit: '必需',
      },
      riskChecks: [],
      operationLogs: [],
      displayCol1: '代课',
      displayCol2: '80% 结算',
      displayCol3: '待核',
      displayCol4: '已发布',
      displayRisk: '—',
    },
    {
      ruleId: 'R-TP-005',
      ruleName: '取消课程不结算',
      segment: 'teacherPay',
      ruleType: '结算条件',
      status: '已发布',
      sensitivity: '重要',
      affectedPorts: ['财务', 'PC 后台'],
      linkedModules: ['课时费'],
      applicableStores: STORES,
      applicableProducts: '—',
      applicableCourseTypes: '全部',
      frontendText: '—',
      backendLogic: '开课前取消成课不计费',
      teacherSideLogic: '—',
      financeImpact: '—',
      contractImpact: '无',
      assetImpact: '—',
      riskTags: [],
      conflictReason: '—',
      missingConfigReason: '—',
      approvalRequired: '财务',
      editableRoles: '财务',
      publishStatus: '已发布',
      updatedBy: '财务 A',
      updatedAt: '2026-01-15 09:00',
      nextAction: '—',
      todaySuggestion: '—',
      judgment: defaultJudgment('已发布', '—', '—'),
      sync: {
        member: '—',
        teacher: '—',
        backend: '取消不计费',
        finance: '—',
        contract: '无',
        audit: '—',
      },
      riskChecks: [],
      operationLogs: [],
      displayCol1: '取消不结算',
      displayCol2: '成课前',
      displayCol3: '—',
      displayCol4: '已发布',
      displayRisk: '—',
    },
    {
      ruleId: 'R-TP-006',
      ruleName: '老师成长等级影响分成',
      segment: 'teacherPay',
      ruleType: '成长',
      status: '草稿',
      sensitivity: '敏感',
      affectedPorts: ['老师端', '财务'],
      linkedModules: ['课时费', '成长'],
      applicableStores: STORES,
      applicableProducts: '—',
      applicableCourseTypes: '—',
      frontendText: '—',
      backendLogic: 'T4+ 分成 +5% 草案',
      teacherSideLogic: '成长摘要可见',
      financeImpact: '待发布',
      contractImpact: '无',
      assetImpact: '—',
      riskTags: [],
      conflictReason: '—',
      missingConfigReason: '—',
      approvalRequired: '总部 + 财务',
      editableRoles: '总部',
      publishStatus: '草稿',
      updatedBy: '总部',
      updatedAt: '2026-05-12 10:00',
      nextAction: '待发布',
      todaySuggestion: '—',
      judgment: defaultJudgment('草稿', '—', '—'),
      sync: {
        member: '—',
        teacher: '等级摘要',
        backend: '草案',
        finance: '待复核',
        contract: '无',
        audit: '—',
      },
      riskChecks: [],
      operationLogs: [],
      displayCol1: '成长等级',
      displayCol2: '+5% 草案',
      displayCol3: '待发布',
      displayCol4: '草稿',
      displayRisk: '—',
    },
    {
      ruleId: 'R-XS-001',
      ruleName: '跨店耗课结算',
      segment: 'crossStore',
      ruleType: '结算',
      status: '已发布',
      sensitivity: '高敏感',
      affectedPorts: ['PC 后台', '财务'],
      linkedModules: ['跨店', '耗课'],
      applicableStores: STORES,
      applicableProducts: '通馆卡',
      applicableCourseTypes: '—',
      frontendText: '跨店说明',
      backendLogic: '按点 80 元 / 点结算',
      teacherSideLogic: '—',
      financeImpact: '待财务复核',
      contractImpact: '无',
      assetImpact: '跨店扣点',
      riskTags: [],
      conflictReason: '—',
      missingConfigReason: '—',
      approvalRequired: '财务 + 总部',
      editableRoles: '财务 / 总部',
      publishStatus: '已发布',
      updatedBy: '财务 B',
      updatedAt: '2026-04-05 11:00',
      nextAction: '—',
      todaySuggestion: '—',
      judgment: defaultJudgment('已发布', '—', '—'),
      sync: {
        member: '跨店预约提示',
        teacher: '—',
        backend: '结算单',
        finance: '门店间结算',
        contract: '无',
        audit: '必需',
      },
      riskChecks: [],
      operationLogs: [],
      displayCol1: '跨店耗课',
      displayCol2: '售卡 / 消课门店',
      displayCol3: '80 元 / 点',
      displayCol4: '已发布',
      displayRisk: '—',
    },
    {
      ruleId: 'R-XS-002',
      ruleName: '单馆卡跨店限制',
      segment: 'crossStore',
      ruleType: '限制',
      status: '已发布',
      sensitivity: '重要',
      affectedPorts: ['会员端', 'PC 后台'],
      linkedModules: ['跨店', '资产'],
      applicableStores: STORES,
      applicableProducts: '单店卡',
      applicableCourseTypes: '—',
      frontendText: '仅限售卡门店使用',
      backendLogic: '非通馆卡不可跨店',
      teacherSideLogic: '—',
      financeImpact: '—',
      contractImpact: '卡项条款',
      assetImpact: '预约拦截',
      riskTags: [],
      conflictReason: '—',
      missingConfigReason: '—',
      approvalRequired: '总部',
      editableRoles: '总部 / 财务',
      publishStatus: '已发布',
      updatedBy: '总部',
      updatedAt: '2026-02-01 09:00',
      nextAction: '—',
      todaySuggestion: '—',
      judgment: defaultJudgment('已发布', '—', '—'),
      sync: {
        member: '跨店拦截提示',
        teacher: '—',
        backend: '规则拦截',
        finance: '—',
        contract: '条款',
        audit: '—',
      },
      riskChecks: [],
      operationLogs: [],
      displayCol1: '单馆卡',
      displayCol2: '不可跨店',
      displayCol3: '—',
      displayCol4: '已发布',
      displayRisk: '—',
    },
    {
      ruleId: 'R-XS-003',
      ruleName: '通馆卡结算',
      segment: 'crossStore',
      ruleType: '通馆',
      status: '已发布',
      sensitivity: '敏感',
      affectedPorts: ['财务'],
      linkedModules: ['跨店'],
      applicableStores: '全馆',
      applicableProducts: '硬核卡 Core / 自由卡 Flex',
      applicableCourseTypes: '—',
      frontendText: '通馆权益说明',
      backendLogic: '总部统一结算池',
      teacherSideLogic: '—',
      financeImpact: '待财务复核',
      contractImpact: '卡项条款',
      assetImpact: '—',
      riskTags: [],
      conflictReason: '—',
      missingConfigReason: '—',
      approvalRequired: '财务',
      editableRoles: '财务 / 总部',
      publishStatus: '已发布',
      updatedBy: '财务 B',
      updatedAt: '2026-03-10 10:00',
      nextAction: '—',
      todaySuggestion: '—',
      judgment: defaultJudgment('已发布', '—', '—'),
      sync: {
        member: '通馆说明',
        teacher: '—',
        backend: '结算池',
        finance: '分馆结算',
        contract: '条款',
        audit: '—',
      },
      riskChecks: [],
      operationLogs: [],
      displayCol1: '通馆卡',
      displayCol2: '结算池',
      displayCol3: '总部',
      displayCol4: '已发布',
      displayRisk: '—',
    },
    {
      ruleId: 'R-XS-004',
      ruleName: '合作门店授权结算',
      segment: 'crossStore',
      ruleType: '合作',
      status: '草稿',
      sensitivity: '敏感',
      affectedPorts: ['PC 后台', '财务'],
      linkedModules: ['跨店'],
      applicableStores: '合作门店',
      applicableProducts: '—',
      applicableCourseTypes: '—',
      frontendText: '—',
      backendLogic: '合作门店名单待发布',
      teacherSideLogic: '—',
      financeImpact: '待定义',
      contractImpact: '合作协议',
      assetImpact: '—',
      riskTags: [],
      conflictReason: '—',
      missingConfigReason: '—',
      approvalRequired: '总部',
      editableRoles: '总部',
      publishStatus: '草稿',
      updatedBy: '总部',
      updatedAt: '2026-05-11 14:00',
      nextAction: '—',
      todaySuggestion: '—',
      judgment: defaultJudgment('草稿', '—', '—'),
      sync: {
        member: '—',
        teacher: '—',
        backend: '草案',
        finance: '待定',
        contract: '合作',
        audit: '—',
      },
      riskChecks: [],
      operationLogs: [],
      displayCol1: '合作门店',
      displayCol2: '授权名单',
      displayCol3: '草案',
      displayCol4: '草稿',
      displayRisk: '—',
    },
    {
      ruleId: 'R-XS-005',
      ruleName: '老师跨店上课结算',
      segment: 'crossStore',
      ruleType: '老师',
      status: '已发布',
      sensitivity: '敏感',
      affectedPorts: ['财务', '老师端'],
      linkedModules: ['跨店', '课时费'],
      applicableStores: STORES,
      applicableProducts: '—',
      applicableCourseTypes: '—',
      frontendText: '—',
      backendLogic: '按消课门店计课时费',
      teacherSideLogic: '跨店课表',
      financeImpact: '待核',
      contractImpact: '无',
      assetImpact: '—',
      riskTags: [],
      conflictReason: '—',
      missingConfigReason: '—',
      approvalRequired: '财务',
      editableRoles: '财务',
      publishStatus: '已发布',
      updatedBy: '财务 A',
      updatedAt: '2026-04-18 11:00',
      nextAction: '—',
      todaySuggestion: '—',
      judgment: defaultJudgment('已发布', '—', '—'),
      sync: {
        member: '—',
        teacher: '跨店课',
        backend: '双规则',
        finance: '课时费 + 跨店',
        contract: '无',
        audit: '—',
      },
      riskChecks: [],
      operationLogs: [],
      displayCol1: '老师跨店',
      displayCol2: '消课门店',
      displayCol3: '课时费',
      displayCol4: '已发布',
      displayRisk: '—',
    },
    {
      ruleId: 'R-NT-001',
      ruleName: '预约成功通知',
      segment: 'notifyPerm',
      ruleType: '通知',
      status: '已发布',
      sensitivity: '普通',
      affectedPorts: ['会员端'],
      linkedModules: ['通知', '预约'],
      applicableStores: STORES,
      applicableProducts: '—',
      applicableCourseTypes: '全部',
      frontendText: '预约成功模板',
      backendLogic: '短信 + 小程序',
      teacherSideLogic: '—',
      financeImpact: '—',
      contractImpact: '—',
      assetImpact: '—',
      riskTags: [],
      conflictReason: '—',
      missingConfigReason: '—',
      approvalRequired: '教务',
      editableRoles: '教务 / 总部',
      publishStatus: '已发布',
      updatedBy: '教务 A',
      updatedAt: '2026-03-01 10:00',
      nextAction: '—',
      todaySuggestion: '—',
      judgment: defaultJudgment('已发布', '—', '—'),
      sync: {
        member: '收到通知',
        teacher: '—',
        backend: '模板配置',
        finance: '—',
        contract: '—',
        audit: '发送日志',
      },
      riskChecks: [],
      operationLogs: [],
      displayCol1: '预约成功',
      displayCol2: '会员',
      displayCol3: '小程序',
      displayCol4: '已发布',
      displayRisk: '—',
    },
    {
      ruleId: 'R-NT-002',
      ruleName: '爽约提醒',
      segment: 'notifyPerm',
      ruleType: '通知',
      status: '配置缺失',
      sensitivity: '重要',
      affectedPorts: ['会员端'],
      linkedModules: ['通知', '预约'],
      applicableStores: STORES,
      applicableProducts: '—',
      applicableCourseTypes: '团课 / 小班',
      frontendText: '—',
      backendLogic: '爽约后通知模板缺失',
      teacherSideLogic: '—',
      financeImpact: '—',
      contractImpact: '—',
      assetImpact: '—',
      riskTags: ['缺失配置'],
      conflictReason: '—',
      missingConfigReason: '爽约通知未配置',
      approvalRequired: '教务',
      editableRoles: '教务 / 总部',
      publishStatus: '未发布',
      updatedBy: '—',
      updatedAt: '—',
      nextAction: '补全模板',
      todaySuggestion: '通知模板缺失',
      judgment: defaultJudgment('配置缺失', '—', '爽约通知缺失'),
      sync: {
        member: '无爽约提醒',
        teacher: '—',
        backend: '逻辑有，通知无',
        finance: '—',
        contract: '—',
        audit: '—',
      },
      riskChecks: ['缺失：通知'],
      operationLogs: [],
      displayCol1: '爽约提醒',
      displayCol2: '会员',
      displayCol3: '未配置',
      displayCol4: '配置缺失',
      displayRisk: '模板缺失',
    },
    {
      ruleId: 'R-NT-003',
      ruleName: '取消成功通知',
      segment: 'notifyPerm',
      ruleType: '通知',
      status: '已发布',
      sensitivity: '普通',
      affectedPorts: ['会员端'],
      linkedModules: ['通知'],
      applicableStores: STORES,
      applicableProducts: '—',
      applicableCourseTypes: '—',
      frontendText: '取消成功',
      backendLogic: '已配置',
      teacherSideLogic: '—',
      financeImpact: '—',
      contractImpact: '—',
      assetImpact: '—',
      riskTags: [],
      conflictReason: '—',
      missingConfigReason: '—',
      approvalRequired: '教务',
      editableRoles: '教务',
      publishStatus: '已发布',
      updatedBy: '教务 B',
      updatedAt: '2026-02-15 09:00',
      nextAction: '—',
      todaySuggestion: '—',
      judgment: defaultJudgment('已发布', '—', '—'),
      sync: {
        member: '取消通知',
        teacher: '—',
        backend: '模板',
        finance: '—',
        contract: '—',
        audit: '日志',
      },
      riskChecks: [],
      operationLogs: [],
      displayCol1: '取消通知',
      displayCol2: '会员',
      displayCol3: '已配置',
      displayCol4: '已发布',
      displayRisk: '—',
    },
    {
      ruleId: 'R-NT-004',
      ruleName: '权限变更留痕',
      segment: 'notifyPerm',
      ruleType: '权限',
      status: '已发布',
      sensitivity: '高敏感',
      affectedPorts: ['PC 后台', '权限审计'],
      linkedModules: ['权限'],
      applicableStores: '总部',
      applicableProducts: '—',
      applicableCourseTypes: '—',
      frontendText: '—',
      backendLogic: '所有权限变更写入审计日志',
      teacherSideLogic: '—',
      financeImpact: '—',
      contractImpact: '—',
      assetImpact: '—',
      riskTags: ['敏感规则'],
      conflictReason: '—',
      missingConfigReason: '—',
      approvalRequired: '总部',
      editableRoles: '总部管理员',
      publishStatus: '已发布',
      updatedBy: '总部',
      updatedAt: '2026-01-01 10:00',
      nextAction: '—',
      todaySuggestion: '—',
      judgment: defaultJudgment('已发布', '—', '—'),
      sync: {
        member: '—',
        teacher: '—',
        backend: '审计日志',
        finance: '—',
        contract: '—',
        audit: '强制',
      },
      riskChecks: ['权限边界'],
      operationLogs: ['2026-01-01 · 启用'],
      displayCol1: '权限审计',
      displayCol2: '全部角色',
      displayCol3: '强制留痕',
      displayCol4: '已发布',
      displayRisk: '高敏感',
    },
    {
      ruleId: 'R-NT-005',
      ruleName: '退款审批通知',
      segment: 'notifyPerm',
      ruleType: '通知',
      status: '已发布',
      sensitivity: '敏感',
      affectedPorts: ['PC 后台', '财务'],
      linkedModules: ['通知', '退款'],
      applicableStores: STORES,
      applicableProducts: '—',
      applicableCourseTypes: '—',
      frontendText: '—',
      backendLogic: '审批节点通知店长 / 财务',
      teacherSideLogic: '不可见',
      financeImpact: '—',
      contractImpact: '—',
      assetImpact: '—',
      riskTags: [],
      conflictReason: '—',
      missingConfigReason: '—',
      approvalRequired: '总部',
      editableRoles: '总部 / 财务',
      publishStatus: '已发布',
      updatedBy: '财务 B',
      updatedAt: '2026-04-01 10:00',
      nextAction: '—',
      todaySuggestion: '—',
      judgment: defaultJudgment('已发布', '—', '—'),
      sync: {
        member: '进度通知',
        teacher: '—',
        backend: '审批提醒',
        finance: '复核节点',
        contract: '—',
        audit: '必需',
      },
      riskChecks: [],
      operationLogs: [],
      displayCol1: '退款审批',
      displayCol2: '店长 / 财务',
      displayCol3: '站内信',
      displayCol4: '已发布',
      displayRisk: '—',
    },
    {
      ruleId: 'R-NT-006',
      ruleName: '老师端课程变更提醒',
      segment: 'notifyPerm',
      ruleType: '通知',
      status: '已发布',
      sensitivity: '普通',
      affectedPorts: ['老师端'],
      linkedModules: ['通知', '排课'],
      applicableStores: STORES,
      applicableProducts: '—',
      applicableCourseTypes: '全部',
      frontendText: '—',
      backendLogic: 'METeach 推送',
      teacherSideLogic: '课表变更推送',
      financeImpact: '—',
      contractImpact: '—',
      assetImpact: '—',
      riskTags: [],
      conflictReason: '—',
      missingConfigReason: '—',
      approvalRequired: '教务',
      editableRoles: '教务',
      publishStatus: '已发布',
      updatedBy: '教务 A',
      updatedAt: '2026-03-20 11:00',
      nextAction: '—',
      todaySuggestion: '—',
      judgment: defaultJudgment('已发布', '—', '—'),
      sync: {
        member: '—',
        teacher: '推送',
        backend: '变更触发',
        finance: '—',
        contract: '—',
        audit: '—',
      },
      riskChecks: [],
      operationLogs: [],
      displayCol1: '课表变更',
      displayCol2: '老师端',
      displayCol3: 'METeach',
      displayCol4: '已发布',
      displayRisk: '—',
    },
  ];

  seeds.push(...moreSeeds);
  return seeds.map((s, i) => mkRule(s, i));
};

const buildKeyImpacts = (r: RuleBase): SettingsKeyImpacts => ({
  booking: r.linkedModules.includes('预约'),
  asset: !/无/.test(r.assetImpact) && r.assetImpact !== '—',
  finance: !/无/.test(r.financeImpact) && r.financeImpact !== '—',
  contract: !/无/.test(r.contractImpact) && r.contractImpact !== '—',
  auditRequired: !/—/.test(r.sync.audit) && r.sync.audit !== '不影响',
});

const buildRiskDetails = (r: RuleBase): SettingsRiskDetailItem[] => {
  const level =
    r.sensitivity === '高敏感' ? '高' : r.sensitivity === '敏感' ? '中' : r.displayRisk !== '—' ? '中' : '低';
  const items: SettingsRiskDetailItem[] = r.riskChecks.map(check => ({
    item: check,
    module: r.linkedModules.join(' / ') || r.ruleType,
    level,
    suggestion: r.judgment.nextStep,
  }));
  if (r.conflictReason !== '—') {
    items.unshift({
      item: '规则冲突',
      module: '三端口径',
      level: '高',
      suggestion: '对齐会员端、PC 后台与老师端后提交审核预览',
    });
  }
  if (r.missingConfigReason !== '—') {
    items.push({
      item: r.missingConfigReason,
      module: '配置完整性',
      level: '中',
      suggestion: '补全配置项后再申请发布预览',
    });
  }
  if (items.length === 0) {
    items.push({
      item: '常规巡检',
      module: r.ruleType,
      level: '低',
      suggestion: r.judgment.nextStep,
    });
  }
  return items.slice(0, 6);
};

const buildVersionLogs = (r: RuleBase): SettingsVersionLogEntry[] => {
  const reason =
    r.conflictReason !== '—' ? r.conflictReason : r.missingConfigReason !== '—' ? r.missingConfigReason : '规则维护';
  return [
    {
      at: r.updatedAt !== '—' ? r.updatedAt : '2026-05-13 09:30',
      by: r.updatedBy !== '—' ? r.updatedBy : '总部规则组',
      action: /草稿|待发布/.test(r.status) ? '修改草稿' : '修改规则',
      reason,
      publishStatus: r.publishStatus,
      note: '前端演示记录',
    },
    {
      at: '2026-05-11 15:20',
      by: '教务 A',
      action: '提交审核预览',
      reason: '提交总部复核',
      publishStatus: '待审核',
      note: '未真实提交',
    },
    {
      at: '2026-05-08 10:00',
      by: '系统',
      action: '创建规则',
      reason: '初始化配置',
      publishStatus: '草稿',
      note: '本页仅展示规则预览',
    },
  ];
};

const enrichSettingsRule = (r: RuleBase): SettingsRuleRow => {
  const unconfiguredItems: string[] = [];
  if (r.missingConfigReason !== '—') unconfiguredItems.push(r.missingConfigReason);
  if (!r.frontendText || r.frontendText === '—') unconfiguredItems.push('前台展示文案未配置');
  if (!r.teacherSideLogic || r.teacherSideLogic === '—') unconfiguredItems.push('老师端执行口径未配置');

  return {
    ...r,
    syncAligned: r.status !== '存在冲突' && r.conflictReason === '—',
    keyImpacts: buildKeyImpacts(r),
    riskDetails: buildRiskDetails(r),
    versionLogs: buildVersionLogs(r),
    unconfiguredItems,
    exampleNote: `示例：${r.ruleName} 生效后，${r.frontendText !== '—' ? r.frontendText : '前台将展示对应说明'}；PC 后台按「${r.backendLogic}」计算。`,
    viewerRoles: '总部管理员 / 店长 / 教务 / 财务（只读）',
    submitterRoles: r.editableRoles,
    publisherRoles: /高敏感|敏感/.test(r.sensitivity) ? '总部管理员' : '总部管理员 / 店长',
  };
};

export const buildSettingsOperationSnapshot = (): SettingsOperationSnapshot => {
  const rules = buildRules().map(enrichSettingsRule);

  const published = rules.filter(r => r.status === '已发布').length;
  const pending = rules.filter(r => /待审核|待发布|草稿/.test(r.status)).length;
  const conflicts = rules.filter(r => r.status === '存在冲突' || r.conflictReason !== '—').length;
  const missing = rules.filter(r => r.status === '配置缺失' || r.missingConfigReason !== '—').length;
  const frontend = rules.filter(r => r.affectedPorts.includes('会员端') || r.affectedPorts.includes('老师端')).length;
  const sensitive = rules.filter(r => r.sensitivity === '敏感' || r.sensitivity === '高敏感').length;

  const metrics: SettingsMetricItem[] = [
    {
      id: 'set-m1',
      label: '已配置规则',
      value: `${rules.length} 条`,
      hint: '课程 / 卡项 / 财务 / 权限',
    },
    {
      id: 'set-m2',
      label: '待审核规则',
      value: `${pending} 条`,
      hint: '修改后未发布',
      tone: 'amber',
    },
    {
      id: 'set-m3',
      label: '规则冲突',
      value: `${conflicts} 项`,
      hint: '前后台口径不一致',
      tone: 'rose',
    },
    {
      id: 'set-m4',
      label: '缺失规则',
      value: `${missing} 项`,
      hint: '冻结 / 转卡 / 通知',
      tone: 'amber',
    },
    {
      id: 'set-m5',
      label: '影响前台',
      value: `${frontend} 条`,
      hint: '会员端 / 老师端可见',
    },
    {
      id: 'set-m6',
      label: '敏感规则',
      value: `${sensitive} 条`,
      hint: '退款 / 权益 / 课时费 / 权限',
      tone: 'rose',
    },
  ];

  const insights: SettingsInsightTip[] = [
    {
      id: 'ins-1',
      tag: '预约取消规则冲突',
      line: '会员端显示与后台配置不一致，建议复核',
      actionLabel: '去复核',
      actionKey: 'booking',
    },
    {
      id: 'ins-2',
      tag: '卡项冻结缺失',
      line: '部分卡项未配置冻结上限，影响资产处理',
      actionLabel: '查看',
      actionKey: 'cardBenefits',
    },
    {
      id: 'ins-3',
      tag: '老师课时费待审',
      line: '课时费规则修改后未发布，影响财务核算',
      actionLabel: '去核对',
      actionKey: 'teacherPay',
    },
    {
      id: 'ins-4',
      tag: '通知模板缺失',
      line: '爽约、候补、取消通知未完整配置',
      actionLabel: '查看',
      actionKey: 'notifyPerm',
    },
  ];

  const actionQueue: SettingsActionItem[] = [
    {
      id: 'sq-1',
      group: 'conflict',
      ruleId: 'R-BK-002',
      title: '开课前 4 小时免费取消',
      statusLabel: '规则冲突',
      riskLine: '会员端 4h / 后台 6h 取消窗口不一致',
      impactChain: ['会员端', 'PC 后台', '财务', '合同'],
      openTab: 'sync',
    },
    {
      id: 'sq-2',
      group: 'conflict',
      ruleId: 'R-BK-002',
      title: '预约取消口径',
      statusLabel: '待对齐',
      riskLine: '影响预约取消与资产回退时点',
      impactChain: ['会员端', 'PC 后台', '资产'],
      openTab: 'risk',
    },
    {
      id: 'sq-3',
      group: 'pendingPublish',
      ruleId: 'R-TP-001',
      title: '团课课时费',
      statusLabel: '待审核',
      riskLine: '课时费规则修改后未发布，财务仍用旧规则',
      impactChain: ['PC 后台', '财务', '老师端'],
      openTab: 'approval',
    },
    {
      id: 'sq-4',
      group: 'pendingPublish',
      ruleId: 'R-CT-003',
      title: '转卡手续费',
      statusLabel: '待发布',
      riskLine: '转卡规则待总部发布',
      impactChain: ['PC 后台', '合同', '资产'],
      openTab: 'approval',
    },
    {
      id: 'sq-5',
      group: 'missing',
      ruleId: 'R-CT-004',
      title: '冻结需原因、天数和有效期处理',
      statusLabel: '配置缺失',
      riskLine: '冻结上限未配置，影响资产冻结处理',
      impactChain: ['会员端', 'PC 后台', '资产'],
      openTab: 'overview',
    },
    {
      id: 'sq-6',
      group: 'missing',
      ruleId: 'R-BK-005',
      title: '候补队列自动递补',
      statusLabel: '模板缺失',
      riskLine: '候补成功通知未配置',
      impactChain: ['会员端', '通知'],
      openTab: 'overview',
    },
    {
      id: 'sq-7',
      group: 'sensitive',
      ruleId: 'R-CT-001',
      title: '退款需审批',
      statusLabel: '高敏感',
      riskLine: '退款需财务复核，不可直接改权益',
      impactChain: ['PC 后台', '财务', '合同', '资产'],
      openTab: 'approval',
    },
    {
      id: 'sq-8',
      group: 'sensitive',
      ruleId: 'R-TP-001',
      title: '团课课时费调整',
      statusLabel: '敏感',
      riskLine: '影响老师收入预估与财务核算',
      impactChain: ['老师端', '财务', 'PC 后台'],
      openTab: 'risk',
    },
  ];

  return { rules, metrics, insights, actionQueue };
};

export const findSettingsRule = (s: SettingsOperationSnapshot, id: string) =>
  s.rules.find(r => r.id === id || r.ruleId === id);

export const filterSettingsRules = (
  rules: SettingsRuleRow[],
  segment: SettingsWorkbenchSegment,
  filters: SettingsListFilters,
): SettingsRuleRow[] => {
  const q = filters.query.trim().toLowerCase();
  return rules.filter(r => {
    if (r.segment !== segment) return false;
    if (filters.status !== '全部' && r.status !== filters.status) return false;
    if (filters.sensitivity !== '全部' && r.sensitivity !== filters.sensitivity) return false;
    if (filters.port !== '全部' && !r.affectedPorts.includes(filters.port)) return false;
    if (filters.conflictOnly && r.status !== '存在冲突' && r.conflictReason === '—') return false;
    if (filters.pendingOnly && !/待审核|待发布|草稿/.test(r.status)) return false;
    if (!q) return true;
    const hay = `${r.ruleName} ${r.ruleId} ${r.applicableProducts} ${r.applicableStores} ${r.affectedPorts.join(' ')} ${r.editableRoles}`.toLowerCase();
    return hay.includes(q);
  });
};

export const computeSettingsSegmentMiniSummary = (
  snapshot: SettingsOperationSnapshot,
  segment: SettingsWorkbenchSegment,
): { label: string; value: string }[] => {
  const rows = snapshot.rules.filter(r => r.segment === segment);
  const published = rows.filter(r => r.status === '已发布').length;
  const pending = rows.filter(r => /待审核|待发布|草稿/.test(r.status)).length;
  const risk = rows.filter(r => r.displayRisk !== '—').length;
  const sensitive = rows.filter(r => r.sensitivity === '敏感' || r.sensitivity === '高敏感').length;
  return [
    { label: '本段规则', value: `${rows.length} 条` },
    { label: '已发布', value: `${published} 条` },
    { label: '待处理', value: `${pending} 条` },
    { label: '风险项', value: `${risk} 项` },
    { label: '敏感', value: `${sensitive} 条` },
  ].slice(0, 4);
};

export const getSegmentLabel = (segment: SettingsWorkbenchSegment): string =>
  SETTINGS_WORKBENCH_SEGMENTS.find(s => s.id === segment)?.label ?? segment;

export const isSettingsEmpty = (value: string | null | undefined): boolean =>
  !value || value === '—' || value === '--';

export const formatSettingsDisplay = (value: string | null | undefined): string | null =>
  isSettingsEmpty(value) ? null : value!;

export const getRuleTodaySuggestion = (rule: SettingsRuleRow): string => {
  if (!isSettingsEmpty(rule.nextAction)) return rule.nextAction;
  if (!isSettingsEmpty(rule.todaySuggestion)) return rule.todaySuggestion;
  return rule.judgment.nextStep;
};

export const SETTINGS_PREVIEW_TOAST =
  '前端演示：需接入真实规则服务、审批流和操作日志后才可提交，未写入系统。';
